function generator$towns_and_cities$oceania_towns(type) {﻿ /* Australia */
	var nm1 = ["Adel", "Al", "Alb", "Alt", "Arm", "Armad", "Ash", "Aub", "Ball", "Balw", "Bath", "Baulkh", "Berw", "Boov", "Boron", "Bris", "Brisb", "Brunsw", "Brunw", "Bud", "Bunb", "Bund", "Burn", "Buss", "Cabool", "Cair", "Cal", "Camb", "Canb", "Carl", "Carn", "Carr", "Cessn", "Chelt", "Clayt", "Cob", "Crag", "Craig", "Cranb", "Cron", "Dand", "Darw", "Dev", "Donc", "Ech", "Elth", "Eng", "Engad", "Epp", "Ess", "Essend", "Forst", "Frem", "Gawl", "Geel", "Ger", "Glad", "Glenm", "Glenr", "Gosn", "Goulb", "Granv", "Griff", "Hawth", "Hob", "Hopp", "Kalg", "Kat", "Kwin", "Lal", "Lanc", "Langw", "Lar", "Lil", "Lilyd", "Lism", "Malv", "Mand", "Mar", "Marr", "Melb", "Melt", "Mild", "Mor", "Morph", "Mosm", "Murr", "Nar", "Ner", "Nowr", "Pak", "Palm", "Param", "Prest", "Randw", "Rowv", "Roxb", "Seaf", "Shepp", "Sidn", "Sunb", "Tamw", "Tar", "Tarn", "Thornl", "Um", "Umin", "Wag", "Wagg", "Wang", "Want", "War", "Warrn", "Werr", "Will", "Wod", "Woll", "Woodr", "Wynd"];
	var nm2 = ["adine", "afton", "agga", "ah", "aide", "ale", "alla", "am", "an", "ana", "ane", "ang", "angba", "antle", "any", "arrin", "art", "arton", "aster", "atta", "ave", "ay", "egie", "eit", "ell", "ells", "en", "endon", "enham", "enong", "er", "erim", "ern", "erra", "errie", "ers", "eston", "ett", "etton", "ibee", "ick", "ide", "ie", "igo", "ilda", "im", "in", "ina", "ine", "ing", "irna", "ith", "on", "ona", "one", "ong", "onga", "ongong", "ool", "oomba", "oorlie", "or", "ora", "ore", "orn", "uca", "ulla", "ura", "urah", "ure", "urn", "ury", "yn"];
	/* Fiji */
	var nm3 = ["Ba", "Bo", "Bra", "Da", "Do", "Dra", "Dre", "Ka", "Ki", "Ko", "La", "Lau", "Le", "Lo", "Lu", "Na", "Nau", "Nu", "Ra", "Rau", "Ro", "Sa", "Sau", "Si", "So", "Ta", "Tau", "To", "Va", "Vo", "Vu"];
	var nm3b = ["ba", "di", "ga", "ka", "ke", "ki", "ku", "ma", "mba", "mi", "ra", "ri", "ro", "ru", "si", "so", "to", "tu", "tum", "va", "vu", "vua"];
	var nm4 = ["basa", "bua", "di", "ka", "kasi", "keti", "ki", "koula", "la", "levu", "mawai", "mi", "nu", "raki", "ri", "rovou", "sa", "savu", "si", "sinu", "sori", "ti", "toka", "tumbua", "vou", "vu", "vua", "vuka", "wai"];
	/* Kiribati */
	var nm5 = ["Aba", "Abai", "Abama", "Abao", "Aenea", "Ai", "Aia", "Am", "An", "Ante", "Aobi", "Aon", "Aoni", "Aono", "Ara", "Auto", "Autu", "Ba", "Bai", "Baka", "Ban", "Bango", "Bare", "Bau", "Benua", "Beta", "Bika", "Bike", "Binoi", "Bonri", "Boro", "Boua", "Bua", "Buari", "Buo", "Ei", "Eri", "Fare", "Faretu", "Kaba", "Kaban", "Kabu", "Kai", "Kan", "Karia", "Kata", "Kau", "Kie", "Koi", "Koina", "Ku", "Kuau", "Makei", "Maki", "Man", "Mane", "Mano", "Manri", "Mare", "Mata", "Mori", "Muri", "Nabei", "Nani", "Napa", "Nawe", "Nawere", "Niku", "Norau", "Nua", "Nuata", "Nuo", "Onee", "Oto", "Rabua", "Rawa", "Rawan", "Rawe", "Ribo", "Rongo", "Rore", "Rotu", "Runga", "Tabe", "Tabi", "Tabo", "Taboi", "Taboma", "Tabon", "Tabu", "Tabui", "Tabuki", "Tabwa", "Taka", "Tama", "Tanae", "Tane", "Tangi", "Tani", "Tanima", "Tara", "Tau", "Taun", "Tboi", "Te", "Teao", "Teari", "Teba", "Teban", "Tebe", "Tebi", "Tebu", "Tebwa", "Tei", "Teka", "Tekabwi", "Tekai", "Tekara", "Tekati", "Tekua", "Tema", "Temai", "Temano", "Tematan", "Temo", "Temwa", "Tenato", "Tene", "Terei", "Teri", "Tetei", "Teua", "Too", "Tuara", "Uban", "Ukia", "Ukian", "Um", "Uteu", "Uti"];
	var nm6 = ["baia", "banga", "bara", "bata", "beina", "benua", "bewa", "biang", "bike", "bo", "bono", "bu", "buaka", "buka", "buna", "burao", "butei", "bwibwi", "gaeaka", "gaki", "garoi", "gata", "getua", "ginako", "ka", "kaka", "kaman", "kao", "kati", "kawa", "ke", "kerai", "ki", "kia", "kiai", "kin", "koro", "kuanga", "ma", "maiaki", "maiku", "mainiku", "makoro", "manu", "mari", "matang", "motu", "naba", "naea", "naeag", "naeang", "nana", "nanuka", "naua", "nawa", "nawi", "neaba", "nebo", "nibai", "niberu", "nibeu", "nikai", "niku", "niman", "noinano", "noku", "nuea", "nuna", "pari", "pia", "rabu", "raeaba", "raereke", "rakan", "ranga", "rano", "rao", "ratai", "rauea", "rawa", "reen", "reke", "reti", "retoa", "ria", "riki", "riko", "rio", "rirake", "roa", "rongo", "rorae", "rua", "ta", "tabi", "tai", "taki", "tania", "tannano", "tao", "tara", "tari", "taw", "tebike", "tebiki", "teman", "tena", "teuea", "teute", "tiam", "tiku", "tio", "tiroa", "toa", "tokia", "ton", "tongo", "toru", "torua", "tukia", "tuma", "wa", "wai", "weai", "were"];
	/* New Zealand */
	var nm7 = ["Ahi", "Aka", "Athe", "Balclu", "Ble", "Blu", "Bur", "Cly", "Coro", "Dar", "Darga", "Dob", "Dune", "Ede", "El", "Embe", "Fai", "Fox", "Gis", "Go", "Hami", "Han", "Haru", "Has", "Have", "Hawe", "Hima", "Hoki", "Inve", "KMas", "Kae", "Kaeo", "Kai", "Kaia", "Kati", "Kaw", "Kawa", "Kawe", "Kel", "Kere", "Keri", "Le", "Lee", "Levi", "Lin", "Make", "Mama", "Man", "Mana", "Mange", "Manu", "Mapu", "Mapua", "Mata", "Mau", "Maun", "Maunga", "Met", "Mil", "Mo", "Moe", "Motue", "Mur", "Muri", "Murra", "Muru", "Na", "Nga", "Ngarua", "Ngu", "Ngun", "Ngungu", "Oa", "Oama", "Oha", "Ohaea", "Oka", "Okai", "Opo", "Opu", "Ota", "Otau", "Oto", "Otoro", "Out", "Ox", "Pa", "Pae", "Paen", "Pai", "Paku", "Papa", "Para", "Parapa", "Paua", "Pe", "Pet", "Pic", "Pori", "Puke", "Ra", "Rag", "Raka", "Ran", "Re", "Repo", "Rive", "Riwa", "Rolle", "Rongo", "Rose", "Rothe", "Roto", "Rox", "Rua", "Rus", "San", "Sed", "Sef", "Tai", "Taka", "Tama", "Tanea", "Tara", "Tau", "Tha", "Ti", "Tima", "Tin", "Titi", "To", "Toko", "Tola", "Tua", "Tuata", "Tura", "Waha", "Wai", "Waiki", "Waio", "Waipa", "Waiu", "Wake", "Walla", "Wama", "Wana", "Wang", "War", "Wave", "Wel", "Whaka", "Whan", "Whanga", "Whi", "Win", "Wood"];
	var nm8 = ["burn", "chison", "coln", "dale", "de", "del", "din", "ganui", "garei", "garoa", "gata", "gere", "gill", "gotea", "guru", "ham", "hanga", "hau", "hi", "hia", "ka", "kai", "kaia", "kaka", "kati", "kau", "kawa", "ke", "kere", "keri", "ketu", "koroa", "koura", "ku", "kuku", "kura", "laga", "lan", "ley", "lie", "lock", "lyn", "maku", "mana", "maru", "mata", "mate", "mes", "naia", "naka", "nake", "ne", "nui", "para", "pawa", "pehi", "pere", "pier", "poi", "pua", "ram", "range", "rangi", "rau", "raumu", "raus", "rays", "re", "ree", "rewa", "riu", "roa", "roto", "rua", "ruru", "son", "ston", "takere", "tane", "tangata", "tangi", "tapere", "tara", "tata", "tati", "tau", "tea", "tianga", "tika", "tiki", "to", "ton", "tone", "torua", "towai", "tueka", "tuke", "turoto", "ven", "vin", "wa", "wahia", "wai", "waka", "wald", "wera", "whata"];
	/* Samoa */
	var nm9 = ["A'o", "A'u", "A'ufa", "Afe", "Afen", "Amai", "Asa", "Aua", "Ava", "Fa", "Faga", "Fai'a", "Fale", "Falea", "Faleo", "Faleu", "Fasi", "Fatu", "Fau", "Fausa", "Fo", "Foga", "Fogasa", "Fu", "Ga", "Gatai", "Gua", "Guata", "Ili'i", "La", "Lalo", "Laloma", "Le", "Lea", "Lele", "Leto", "Leu", "Leulu", "Lo", "Loto", "Lu", "Lufi", "Maa", "Mana", "Mani", "Manu", "Mata", "Matau", "Muli", "Musu", "Mutia", "Nefu", "Niu", "Niusua", "No", "Nofoa", "Pa", "Pai", "Pata", "Pou", "Pu", "Sa", "Sa'a", "Safo", "Sago", "Sai", "Saipi", "Sala", "Sale", "Sale'", "Sale'a'", "Salei", "Salei'", "Salesa", "Sali", "Sama", "Samau", "Samu", "Sapa", "Sapo'", "Sapu", "Sasi", "Sata", "Sati", "Satui", "Sau", "Sava", "Si", "Si'u", "Siu", "Siuse", "Solo", "Ta", "Tae", "Taele", "Tafa", "Tafi", "Tapue", "Toa", "Tua", "Tufu", "Uafa", "Ulu", "Utu", "Vai", "Vaia", "Vaiu", "Vao"];
	var nm10 = ["aula", "fa", "faga", "fanua", "fato", "fau", "fenga", "fotu", "fua", "ga", "gaga", "galu", "gamanu", "gia", "giagi", "gone", "la", "lae", "laelae", "laeulu", "lafa", "lalafa", "lava", "le", "leele", "lefa", "leia", "lele", "leolo", "lepa", "lesi", "leula", "li'i", "lie", "lima", "limu", "livai", "loa", "lovi", "lua", "lufi", "lupo", "maile", "malava", "malo", "mamea", "manu", "matau", "mauga", "mea", "moega", "mua", "musu", "na", "naoa", "nase", "nefu", "niatu", "ninoa", "no", "nofo", "nunu", "pa", "pali'i", "papa", "pea", "pia", "pipi", "po", "po'e", "pouli", "puala", "pulu", "puna", "sa'ai", "saga", "sala", "satele", "sau", "savai'i", "sega", "si", "sina", "sivi", "soali'i", "solo", "su", "suatia", "ta", "tafa", "tafoe", "taivai", "talo", "tamea", "tasi", "taua", "tautu", "tavai", "tele", "tia", "titoa", "toala", "togia", "togo", "tu", "tufu", "tui", "tuli", "vai", "vaia", "valu", "vao", "vau", "vi"];
	/* Tonga */
	var nm11 = ["Ale", "Anga", "Faka", "Fale", "Fan", "Fata", "Fata'u", "Fatu", "Fe", "Fele", "Feto", "Fo", "Foa", "Fola", "Fongo", "Fonoi", "Fonuai", "Fotu", "Ha'a", "Ha'u", "Hakau", "Hakaua", "Hala", "Hamu", "Have", "Hihi", "Ho", "Hoi", "Hoku", "Holo", "Hota'", "Hou", "Hun", "Ka", "Kala", "Kano", "Kao", "Kape", "Kele", "Kito", "Ko", "Kolo", "Kotu", "Kou", "Lake", "Lalo", "Lapa", "Lave", "Leke", "Lete", "Li", "Lifu", "Lofa", "Lon", "Loto", "Lua", "Luen", "Lulu", "Lulun", "Makau", "Mala", "Man", "Mana", "Manu", "Masi", "Mata", "Mata'a", "Matan", "Matu", "Me", "Mea", "Mine", "Mo'u", "Mo'un", "Mui", "Nako", "Navu", "Neia", "Nini", "Niu", "Niua", "Nomu", "Nu", "Nuku", "Ofo", "Pan", "Pe", "Pele", "Peta", "Pu", "Puko", "Putu", "Sapa'a", "Sikai", "So", "Ta", "Tafa", "Tafu", "Tala", "Tata", "Tava", "Te'e", "Tefi", "Tele", "To", "Tofa", "Ton", "Tonga", "Tongo", "Tonu", "Topue", "Tu'u", "Tun", "Uo", "Uole", "Uonu", "Vai", "Vao"];
	var nm12 = ["fahi", "faiau", "fanga", "fesia", "feva", "fio", "fisi", "fo'ou", "foa", "fonua", "fua", "fuiva", "fuka", "ga", "ga'one", "gaha", "gahu", "gai", "gale", "gana", "giake", "go", "goii", "gua", "ha'a", "hahake", "hake", "hau", "hi", "hifo", "hihifo", "hoko", "ifo", "ka", "kakai", "katolo", "kauata", "kelau", "kepa", "kili", "kolo", "ku", "kuanga", "kula", "kulei", "kulu", "kupolu", "kupule", "lala", "lalo", "lamea", "langa", "lapo", "lau", "leka", "leleka", "leloa", "leva", "liku", "lo", "loa", "lona", "longa", "lunga", "ma", "ma'o", "maka", "mama'o", "manongi", "mea", "motu", "mu", "muka", "mula", "naka", "namo", "niva", "noa", "nongi", "nua", "nuaika", "nuka", "numea", "paha", "peka", "poa", "polu", "pu", "pule", "punga", "putapu", "putua", "sia", "ta'ane", "tafa", "tafu", "tala", "tani", "tapu", "teo'o", "to", "toa", "toka", "tolo", "tonga", "tu", "tu'u", "tua", "tuku", "tula", "tumu", "va", "vili", "viti"];


	i = Math.floor(Math.random() * 12); {
		if (i < 2) {
			rnd = Math.floor(Math.random() * nm1.length);
			rnd2 = Math.floor(Math.random() * nm2.length);
			names = nm1[rnd] + nm2[rnd2];
		} else if (i < 4) {
			rnd = Math.floor(Math.random() * nm3.length);
			rndb = Math.floor(Math.random() * nm3b.length);
			rnd2 = Math.floor(Math.random() * nm4.length);
			names = nm3[rnd] + nm3b[rndb] + nm4[rnd2];
		} else if (i < 6) {
			rnd = Math.floor(Math.random() * nm5.length);
			rnd2 = Math.floor(Math.random() * nm6.length);
			names = nm5[rnd] + nm6[rnd2];
		} else if (i < 8) {
			rnd = Math.floor(Math.random() * nm7.length);
			rnd2 = Math.floor(Math.random() * nm8.length);
			names = nm7[rnd] + nm8[rnd2];
		} else if (i < 10) {
			rnd = Math.floor(Math.random() * nm9.length);
			rnd2 = Math.floor(Math.random() * nm10.length);
			names = nm9[rnd] + nm10[rnd2];
		} else if (i < 12) {
			rnd = Math.floor(Math.random() * nm11.length);
			rnd2 = Math.floor(Math.random() * nm12.length);
			names = nm11[rnd] + nm12[rnd2];
		}
		return names;
	}

}