var nm1 = ["area", "city", "country", "district", "empire", "nation", "province", "realm", "region", "remote town", "remote village", "state", "territory", "town", "village"];
var nm2 = ["B", "C", "D", "F", "G", "H", "I", "J", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "X", "Y", "Z"];
var nm3 = ["a", "e", "o", "u"];
var nm4 = ["br", "cr", "dr", "fr", "gr", "pr", "str", "tr", "bl", "cl", "fl", "gl", "pl", "sl", "sc", "sk", "sm", "sn", "sp", "st", "sw", "ch", "sh", "th", "wh"];
var nm5 = ["ia", "a", "en", "ar", "istan", "aria", "ington", "ua", "ijan", "ain", "ium", "us", "esh", "os", "ana", "il", "ad", "or", "ea", "eau", "ax", "on", "ana", "ary", "ya", "ye", "yae", "ait", "ein", "urg", "al", "ines", "ela"];
var nm6 = [
	[
		["men to prepare a special meal", "men to dress up in traditional clothing", "men to create a traditional work of art", "men to decorate the house", "men to carry out an act of kindness for a stranger", "men to perform in a ceremonial duel", "men to take special care of the family's elders", "men to clean and fix up their homes", "men to isolate themselves for a period of time and meditate", "men to perform a ritualistic and intimidating dance", "men to tell a legendary tale of old", "men to hunt an animal to be used as food for their family", "men to perform in a traditional play", "men to clean and decorate the graves of their ancestors", "men to get a traditional tattoo", "men to prove their bravery and intelligence in a traditional hunt", "men to recite religious texts to bless their homes and family", "men to perform a dance to illustrate their family history", "men to reenact a famous duel", "men to profess their love, if they are indeed in love", "men to live completely alone for a period of time", "men to go out in nature with their fathers to survive on nature", "men to fast for a period of time", "men to donate part of their income", "men to walk barefoot for a period of time", "men to give the women they hold dear gifts", "men to 'decorate' their significant other with special paints and make up", "men to remind the groom's they were best man for of the groom's wedding vows", "men to plant vegetables and other food in a community plot of land", "men to shave their heads"],
		["compassion", "confidence", "courage", "creativity", "decisiveness", "discipline", "duty", "elegance", "generosity", "humbleness", "independence", "individualism", "integrity", "intelligence", "loyalty", "masculinity", "maturity", "patience", "respect", "selflessness", "stability", "strength", "their capability", "trust"]
	],
	[
		["women to dress up in their finest clothes", "women to braid their hair", "women to sing a traditional song for their ancestors", "women to prepare a traditional meal", "women to decorate their homes", "women to be bathed in gifts and appreciation", "women to give a gift to the person they hold most dear", "women to prepare a traditional ornament piece", "women to light their homes with just candles", "women to wear perfume they made themselves", "women to drink a home-brewed alcoholic drink", "women to craft and gift a traditional lantern", "women to prepare a meal just for themselves", "women to camp for a night at the graves of their ancestors", "women to decorate their faces with intimidating designs", "women to hide small gifts around their homes", "women to cook a meal with their children and/or mothers", "women to wear a traditional mask", "women to catch a small animal", "women to try and hide from their significant other for a period of time", "women to create a handmade gift for their significant other", "women to create and wear a traditional piece of clothing", "women to demonstrate their skill with a weapon of choice", "women to prepare and lit a special bonfire", "women to profess their love, if they are indeed in love", "women to fast for a period of time", "women to live in isolation for a period of time", "women to get a traditional, temporary tattoo", "women to take care of all the children in the family for a period of time", "women to prepare a meal for a stranger"],
		["attractiveness", "caring", "charm", "compassion", "confidence", "creativity", "decisiveness", "discipline", "empathy", "femininity", "generosity", "grace", "humbleness", "independence", "individualism", "intelligence", "kindness", "loyalty", "maturity", "patience", "selflessness", "tenderness", "their capability", "trust"]
	],
	[
		["people to burn a homemade doll", "people to wear multi-colored clothes", "people to hang dozens of bells around their homes", "people to hide coins in food", "people to prepare a feast of sugary foods", "people to hold jumping contests", "people to throw various spices on each other", "people to pour water on each other", "people to spend a night at an ancestor's grave", "people to hack old furniture to pieces", "people to hug cattle and other other large animals", "people to carve animals from pieces of wood", "people to throw flower petals on people who are single", "people to throw old shoes onto tree branches", "people to place a stack of coins at their doorsteps", "people to greet all crows", "people to drink alcohol infused teas", "people to attempt to communicate with the dead", "people to pour clean water on their own shadows", "people to light their homes with only candles", "people to hang lanterns outside their front doors", "people to create and then destroy homemade effigies", "people to try to scare each other", "people to throw sugar on the streets", "people to place plates of food outside their doors", "people to hang an animal skull outside their front doors", "people to bake a cake and trade it with others", "people to wear white clothes before throwing paint at each other", "people to throw sticky food at the ceiling and hope it sticks", "people to walk across a frozen lake"],
		["attractiveness", "caring", "charm", "compassion", "confidence", "courage", "creativity", "decisiveness", "discipline", "duty", "elegance", "empathy", "generosity", "grace", "humbleness", "independence", "individualism", "integrity", "intelligence", "kindness", "loyalty", "maturity", "patience", "respect", "selflessness", "stability", "strength", "tenderness", "their capability", "trust"]
	]
];
var nm7 = ["rite of passage", "coming of age ritual or festivity", "religious ritual or festivity", "spiritual ritual or festivity", "larger celebration", "type of initiation into a new part of life", "type of honoring ritual", "larger ceremony", "larger ceremonial performance", "larger life ceremony", "greater festival and festivities"];
var nm8 = ["last for days", "last for several days", "last for a day or two", "last for a day", "last for a week", "last for an entire week", "last for up to a week", "last for almost a week", "last for half a week", "last for over a week"];
var nm9 = ["once they become adults", "once they're a certain age", "once a year", "once every six months", "on the summer solstice", "on the winter solstice", "every solstice", "on a specific date of the year", "on the first full moon of the year", "on the first day of the third month"];
var nm10 = [
	[
		["to surround a deceased person with scented candles", "to cover a deceased person in flower petals", "to break all the mirrors in the house of somebody after they die", "to carry the thinly covered body of a deceased person to their final resting place", "to play loud music for 24 hours after somebody dies", "to darken a room completely for 24 hours after somebody dies", "to dance in a circle around a recently deceased person", "to shave the hair of a deceased person", "to blindfold the dead", "to leave a plate of food next to a recently deceased person for up to 24 hours", "to make the faces of the deceased appear to be smiling", "to open the mouths of the deceased", "to lay the deceased on their stomachs instead of their back", "to paint the faces of the deceased with intimidating designs", "to tie the hands and feet of the deceased", "to cover the eyes, ears and mouths of the deceased", "to cover or otherwise obstruct the view of all the pictures of the recently deceased", "to leave a watch with the time of death with the recently deceased", "to destroy whichever piece of furniture somebody died in", "to burn the clothes worn by somebody at their time of death", "to destroy the most precious item of the recently deceased", "to cover the face of the deceased with a mask", "to not interact with the recently deceased for up to 5 days", "to disguise the recently deceased by altering their appearance", "to make sure the recently deceased are always touched by sunlight or candle light", "to lock the recently deceased in the room they died in for up to 4 days", "to surround the recently deceased with as much silence as possible for a period of time", "to sing traditional songs to the recently deceased", "to burn the bed of a deceased person", "to take a picture of a recently deceased person and immediately burn it"],
		["aid the spirit of the deceased on its journey to the afterlife", "break the bond the spirit of the deceased might still have with this world", "ease the journey of the spirit", "guide the spirit of the deceased to the next world", "help both the spirit of the deceased and the mourning process of the living", "help the living with their mourning process", "help the spirit of the deceased come to terms with death", "help the spirit of the deceased find the spirits of its ancestors", "help the spirits of the ancestors identify their new member", "make sure the spirit of the deceased is guided by the right forces", "prevent evil spirits from taking the body of the deceased", "prevent the spirit of the deceased from becoming corrupted", "prevent the spirit of the deceased from trying to return", "prevent the spirit of the deceased to become attached to this world", "protect the deceased against evil spirits"]
	],
	[
		["to marry on a Monday, Wednesday or Friday", "to carry the bride to the altar without allowing her feet to touch the ground", "to hide a golden coin in the suit of the groom", "to gift a newly wed couple a young tree", "to make a newly wed couple walk across fertile soil", "to throw paint at a newly wed couple after their ceremony", "to wear the colors of both sides of the family when a couple gets married", "to light a new fire from a torch from each side of the family when a couple gets married", "to dance barefoot at a wedding", "to gift a newly wed couple sweets and desserts", "to stand on 2 golden coins when speaking your wedding vows", "to tie ribbons to the bride's dress which are later pulled by the bridesmaids", "to paint the faces of a couple who's about the marry", "to wear masks until the moment you say your wedding vows", "to stop shaving for a month prior to the wedding", "for a couple to live apart for a week prior to their wedding", "for a couple to prepare at least 1 dish to be eaten at the wedding party ", "for a couple not to sleep in the same bed the night before their wedding", "to wear a crown of flowers when you get married", "to exchange 2 pairs of rings when you get married", "to paint half their faces when they get married", "to reveal deep secrets of a couple on their wedding day", "to remain silent for the entirety of your own wedding day", "to bind the hands of a couple with a ribbon on their wedding day", "to throw ribbons with messages on a couple on their wedding day", "to make the first kiss on your wedding day last 1 minute", "to bring a baby to a wedding", "for a couple not to eat anything on their own wedding", "to be blindfolded when you get married", "to lock all the doors when a wedding takes place"],
		["bring fortune to the married couple", "bless the new life of the married couple", "bless the married couple and their families", "ensure a happy life for the newly wed couple", "bring health and fortune to the newly wed couple", "unite the families of the married couple", "purify the couple and bless their new united life together", "brighten the future of the married couple", "strengthen the bond between the now united couple"]
	],
	[
		["to give a new born baby a gold coin", "to whisper a wish to a new born baby", "to paint a new born baby's face", "to gift a new born baby various seeds", "to wrap a new born baby in the bed sheets of the parents", "to prevent a new born baby from touching the ground with its bare feet for 1 year", "to ignore other people's babies until they're at least 1 year old", "to make a baby wear a mask until it is 3 months old", "to mark a new born baby's forehead with a painted symbol", "to gift a new born baby an item of the oldest living person in the family", "to not wash a new born baby until it is 1 month old and prevent it from getting dirty", "to receive a gift from the baby (actually the parents) when visiting the baby after it has been born", "for grandparents to be the first to kiss a new born baby", "to gift a new born baby symbolic items representing each of its family members", "to make a new born baby hold your wallet or money", "to give a new born baby a gentle massage", "to gaze into the eyes of a new born baby for at least 1 minute", "for grandmothers to be the first to sing a song to new born babies", "to wrap a ribbon around a new born baby's left wrist", "to touch the feet of a new born baby", "to avoid eye contact with a new born baby (except your own) until it is 1 month old", "to make a baby touch the front door of its home before entering it for the first time", "to make a new born baby touch your forehead", "to make a new born baby hold the hands of both its parents", "to gift a new born baby something you hold dear", "to kiss the hands of a new born baby", "to cover a new born baby's belly with your hand when you meet it for the first time", "to make a new born baby laugh. You can't stop trying until it does", "to gift a new born baby something you made yourself", "to gift a new born baby herbs and spices"],
		["bless the baby and bring it fortune and health", "bring good fortune and health", "bless the lives of all those around the baby", "create and strengthen a bond", "be an omen of good fortune", "be a most fortunate blessing"]
	]
];

function generator$descriptions$traditions() {

	var rnd1 = Math.floor(Math.random() * nm1.length);
	var rnd2 = Math.floor(Math.random() * nm2.length);
	var rnd3 = Math.floor(Math.random() * nm3.length);
	var rnd4 = Math.floor(Math.random() * nm4.length);
	var rnd5 = Math.floor(Math.random() * nm5.length);
	var rnd6 = Math.floor(Math.random() * nm6.length);
	var rnd6b = Math.floor(Math.random() * nm6[rnd6][0].length);
	var rnd6c = Math.floor(Math.random() * nm6[rnd6][1].length);
	var rnd6d = Math.floor(Math.random() * nm6[rnd6][1].length);
	while (rnd6c === rnd6d) {
		var rnd6d = Math.floor(Math.random() * nm6[rnd6][1].length);
	}
	var rnd7 = Math.floor(Math.random() * nm7.length);
	var rnd8 = Math.floor(Math.random() * nm8.length);
	var rnd9 = Math.floor(Math.random() * nm9.length);

	var rnd10 = Math.floor(Math.random() * nm1.length);
	var rnd11 = Math.floor(Math.random() * nm2.length);
	var rnd12 = Math.floor(Math.random() * nm3.length);
	var rnd13 = Math.floor(Math.random() * nm4.length);
	var rnd14 = Math.floor(Math.random() * nm5.length);
	var rnd15 = Math.floor(Math.random() * nm10.length);
	var rnd15b = Math.floor(Math.random() * nm10[rnd15][0].length);
	var rnd15c = Math.floor(Math.random() * nm10[rnd15][1].length);


	var name = "In the " + nm1[rnd1] + " of " + nm2[rnd2] + nm3[rnd3] + nm4[rnd4] + nm5[rnd5] + " it is tradition for " + nm6[rnd6][0][rnd6b] + " " + nm9[rnd9] + ". It's supposed to be a symbol of " + nm6[rnd6][1][rnd6c] + " and " + nm6[rnd6][1][rnd6d] + " and it's usually part of a " + nm7[rnd7] + " that can " + nm8[rnd8] + ".";
	var name2 = "-------------------------"
	var name3 = "In the " + nm1[rnd10] + " of " + nm2[rnd11] + nm3[rnd12] + nm4[rnd13] + nm5[rnd14] + " it is tradition " + nm10[rnd15][0][rnd15b] + ". It's supposed to " + nm10[rnd15][1][rnd15c] + ".";



	var result = "";
	result += name;
	result += "\n";
	result += "\n";
	result += name2;
	result += "\n";
	result += "\n";
	result += name3;
	return result;
}