var nm1 = ["Ar", "Are", "Ba", "Bra", "Bri", "Da", "Dha", "Dra", "Dri", "Dru", "Gar", "Gara", "Gna", "Gnar", "Gno", "Gnu", "Gra", "Gri", "Gru", "Gun", "Hon", "Hun", "Ja", "Jan", "Jar", "Kal", "Kan", "Kha", "Khu", "Kon", "Kul", "Man", "Min", "Mo", "Moh", "Mohr", "Mon", "Mu", "Mun", "Mur", "Na", "Ni", "No", "Nohr", "Nu", "Nur", "Par", "Pra", "Pru", "Ra", "Rahd", "Ran", "Rat", "Ren", "Ret", "Ri", "Ril", "Ro", "Ru", "Rut", "Sir", "Su", "Sur", "Sy", "Syn", "Syr", "Te", "Tin", "Tra", "Tu", "Tuhr", "Tun", "Tur", "Ty", "Tyr", "Va", "Vo", "Vra", "Vru", "Vu", "Vy", "Vyr", "Wan", "War", "Wra", "Wri", "Wru", "Wry", "Wu", "Wun", "Wur", "Wy", "Wyr", "Xa", "Xin", "Xu", "Xur", "Xy", "Za", "Zam", "Zan", "Zu", "Zun", "Zy", "Zyr"];
var nm2 = ["ban", "bur", "barun", "baruk", "buk", "bur", "bor", "dor", "duk", "drun", "dius", "bius", "bus", "dus", "dir", "drak", "dax", "diax", "frad", "farak", "gun", "grak", "garan", "garak", "gur", "grin", "grim", "gon", "jur", "jak", "jag", "jius", "jus", "kius", "kus", "kiras", "kirus", "kas", "kurun", "kud", "kod", "kohr", "khius", "khus", "mius", "mus", "meus", "muk", "maruk", "mud", "miud", "mun", "myr", "myar", "mier", "mak", "neus", "nus", "nius", "nuk", "nur", "nuran", "narak", "nas", "nax", "max", "nyr", "nag", "phas", "phius", "pheus", "phus", "pius", "peus", "prak", "parak", "prix", "rad", "ruk", "radak", "ras", "rius", "reus", "rus", "rios", "rath", "rakar", "rag", "ragar", "rug", "rahg", "raz", "rax", "ryx", "rox", "sius", "sus", "seus", "sus", "sag", "sug", "sur", "sar", "tor", "thur", "tir", "trak", "tagar", "tarak", "truk", "tus", "tius", "teus", "tin", "tak", "vak", "vius", "veus", "vis", "vur", "vas", "zius", "zeus", "zus", "zak", "zur", "zan", "zun"];
var nm3 = ["Aer", "Ane", "Bae", "Bera", "Bli", "De", "Dhi", "Dra", "Dre", "Dry", "Ger", "Gera", "Gna", "Gne", "Gner", "Gni", "Gra", "Gre", "Gren", "Gri", "Hel", "Hil", "Hin", "Jer", "Jin", "Kal", "Kan", "Kel", "Kha", "Khe", "Kon", "Mae", "Me", "Mehr", "Men", "Min", "Mir", "Moh", "Mol", "Na", "Nehl", "Nes", "Ni", "Nia", "No", "Pha", "Phe", "Phi", "Phra", "Pre", "Pri", "Ran", "Reh", "Rel", "Res", "Rhe", "Ri", "Rihl", "Rin", "Ris", "Ro", "She", "Shy", "Sil", "Syl", "Syn", "Syr", "Te", "Tel", "Ten", "The", "Tis", "Trae", "Trih", "Ty", "Tys", "Va", "Ve", "Vo", "Vre", "Vry", "Vy", "Vyl", "Wa", "Waer", "Wan", "Was", "Wen", "Wi", "Wre", "Wri", "Wry", "Wy", "Wys", "Xa", "Xe", "Xel", "Xil", "Xy", "Za", "Zam", "Zan", "Zen", "Zha", "Zy", "Zyl"];
var nm4 = ["barin", "bea", "bei", "ben", "bes", "bis", "bise", "bur", "bura", "dea", "deha", "den", "dia", "dira", "dis", "dris", "dya", "fera", "frae", "gara", "garis", "gea", "gen", "gera", "geth", "gres", "ja", "jei", "jia", "jice", "kea", "kena", "kes", "keth", "khia", "khis", "kira", "kis", "ko", "kohn", "ma", "mara", "mas", "mel", "mes", "meth", "mia", "mien", "min", "mira", "mis", "mya", "mys", "naga", "nara", "nea", "nes", "ness", "neth", "nira", "niras", "nis", "nith", "nys", "para", "pea", "phas", "pheras", "phes", "phin", "phis", "pia", "pria", "ra", "rada", "rae", "rah", "rala", "ran", "rasha", "rea", "rena", "res", "resh", "reth", "ria", "ris", "rya", "ryl", "sa", "sara", "sen", "sesh", "sia", "sien", "sira", "sis", "tana", "tera", "tes", "teus", "thea", "tia", "tin", "tis", "tish", "tren", "tris", "vash", "ven", "vera", "ves", "via", "vien", "zana", "zel", "zen", "zeph", "zera", "zia", "zis"];
var nm5 = ["Ag", "Al", "Ba", "Be", "Ben", "De", "Dhe", "Dhi", "Dra", "Dro", "Gen", "Ger", "Gin", "Gna", "Gne", "Gra", "Gre", "Gren", "Gri", "Hal", "Has", "Hon", "Jan", "Jen", "Kal", "Kan", "Kel", "Ker", "Kha", "Kon", "Ma", "Mahr", "Man", "Mas", "Me", "Mer", "Min", "Mon", "Na", "Nal", "Nar", "Ni", "No", "Nor", "Pa", "Par", "Per", "Pha", "Pra", "Pre", "Ram", "Ran", "Ras", "Reg", "Rel", "Ren", "Rho", "Ri", "Rin", "Ro", "Sal", "Sar", "Sen", "Sil", "Syn", "Syr", "Te", "Tel", "Ten", "Tha", "Tir", "Tra", "Tri", "Ty", "Tyn", "Va", "Ve", "Ven", "Vo", "Vra", "Vri", "Vy", "Wa", "Wal", "Wen", "Wer", "Wes", "Wi", "Win", "Wre", "Wy", "Wyn", "Xa", "Xe", "Xel", "Xil", "Xy", "Za", "Zam", "Zan", "Zen", "Zha", "Zy", "Zyl"];
var nm6 = ["ba", "ban", "ben", "ber", "beth", "bin", "bis", "bith", "da", "del", "den", "des", "dis", "dith", "dres", "dyn", "fer", "fra", "ga", "gan", "gen", "ger", "ges", "geth", "gres", "ja", "jas", "jia", "jis", "ka", "kan", "kas", "keas", "kel", "ken", "kha", "khes", "kir", "kohn", "ma", "mal", "mar", "mara", "mas", "mes", "mian", "min", "mir", "mis", "mor", "myas", "mys", "na", "nag", "nar", "ned", "nes", "neth", "nig", "nir", "nis", "nith", "nys", "pan", "par", "pas", "phas", "pheran", "phes", "phin", "phis", "ra", "rada", "rah", "raja", "ral", "ran", "ras", "rash", "rasha", "ren", "rena", "res", "rija", "rith", "ryan", "ryn", "sal", "sar", "sen", "sien", "sin", "sir", "sis", "tara", "taren", "ten", "tera", "tes", "teus", "tha", "tin", "tish", "tix", "tres", "vas", "vel", "ven", "ver", "vin", "vir", "zan", "zel", "zen", "zeph", "zera", "zia", "zis"];

function generator$fantasy$minotaurs(type) {

	i = Math.floor(Math.random() * 10); {
		if (type === 1) {
			rnd = Math.floor(Math.random() * nm3.length);
			rnd2 = Math.floor(Math.random() * nm4.length);
			names = nm3[rnd] + nm4[rnd2];
		} else if (type === 2) {
			rnd = Math.floor(Math.random() * nm5.length);
			rnd2 = Math.floor(Math.random() * nm6.length);
			names = nm5[rnd] + nm6[rnd2];
		} else {
			rnd = Math.floor(Math.random() * nm1.length);
			rnd2 = Math.floor(Math.random() * nm2.length);
			names = nm1[rnd] + nm2[rnd2];
		}
		return names;
	}

}