function generator$real$aztecs(type) {
	var nm1 = ["Acalan", "Acamapichtli", "Achcauhtli", "Acolmixtli", "Ahuiliztli", "Ahuitzotl", "Amoxtli", "Atl", "Axayacatl", "Camaxtli", "Chicahua", "Chimalli", "Chimalpopoca", "Chipahua", "Cipac", "Cipactli", "Citlali", "Citlalli", "Coatl", "Coyotl", "Cozahtli", "Cualli", "Cuauhtemoc", "Cuauhtl", "Cuetlachtli", "Cuetzpalli", "Cuixtli", "Ehecatl", "Eleuia", "Eloxochitl", "Etalpalli", "Eztli", "Huemac", "Huitzilihuitl", "Huitzilin", "Huitzilli", "Huitzitl", "Huitztecol", "Iccauhtli", "Ichtaca", "Icnoyotl", "Ihuicatl", "Ilhicamina", "Ilhuitl", "Itotia", "Itzcali", "Itzcoatl", "Itzcuintli", "Itzli", "Itztli", "Iuitl", "Ixtli", "Ixtlilxochitl", "Izel", "Mahuizoh", "Manauia", "Matlal", "Matlalihuitl", "Maxtla", "Mazatl", "Mecatl", "Meztli", "Mictlantecuhtli", "Milintica", "Miztli", "Momoztli", "Montezuma", "Moquihuix", "Moyolehuani", "Nahuatl", "Namacuix", "Natlalihuitl", "Necahual", "Necalli", "Necuametl", "Nelli", "Nezahualcoyotl", "Nezahualpilli", "Nochehuatl", "Nochtli", "Nopaltzin", "Ocelotl", "Ocuil", "Ohtli", "Olli", "Ollin", "Ozomatli", "Patli", "Quauhtli", "Quetzalcoatl", "Tapayaxi", "Tecolotl", "Tenoch", "Teoxihuitl", "Tepiltzin", "Tepin", "Tezcacoatl", "Tezozomoc", "Tizoc", "Tlacaelel", "Tlacelel", "Tlachinolli", "Tlalli", "Tlaloc", "Tlanextic", "Tlanextli", "Tlazohtlaloni", "Tlazopilli", "Tlexictli", "Tlilpotonqui", "Tochtli", "Toltecatl", "Tonauac", "Topiltzin", "Tototl", "Tupac", "Ueman", "Uetzcayotl", "Xicohtencatl", "Xihuitl", "Xipil", "Xipilli", "Xiuhcoatl", "Xiuhpilli", "Xochipepe", "Xochipilli", "Xochitl", "Yaotl", "Yayauhqui", "Yolotli", "Yolyamanitzin", "Zipactonal", "Zolin", "Zuma"];
	var nm2 = ["Achcauh", "Ahuiliz", "Amox", "Azcalxochi", "Cente", "Chalchiuh", "Chalchiui", "Chica", "Chicome", "Chimal", "Chipa", "Cihua", "Citla", "Citlal", "Coa", "Coszca", "Cozama", "Cual", "Cuica", "Eloxo", "Eren", "Etal", "Ez", "Hue", "Huitzil", "Huitzili", "Iccauh", "Ich", "Icnoyo", "Ihuica", "Ilhica", "Ilhui", "Ito", "Itz", "Iui", "Ix", "Ixca", "Mahui", "Malinal", "Maza", "Meca", "Mez", "Miahua", "Miyaoa", "Mizqui", "Momoz", "Moyole", "Nahua", "Neca", "Nel", "Nene", "Noch", "Noxochi", "Oh", "Pa", "Que", "Quetzal", "Quiauh", "Sac", "Te", "Tei", "Teoxi", "Teui", "Teya", "Tla", "Tlachi", "Tlah", "Tlal", "Tlanex", "Tlazoh", "Tlexic", "Toch", "Tolte", "Tonal", "Xi", "Xihui", "Xilo", "Xio", "Xitlal", "Xiuh", "Xo", "Xochi", "Xoco", "Yao", "Yare", "Yayauh", "Yol", "Yoli", "Yolo", "Yolyamani", "Zani", "Zel", "Zya"];
	var nm3 = ["capan", "catl", "chel", "chitl", "co", "coatl", "coehua", "coh", "cotl", "cotzin", "coztli", "cui", "cuih", "dira", "hua", "hual", "huani", "huitl", "li", "lotl", "ma", "mac", "mara", "mina", "nan", "nen", "nite", "noch", "nolli", "nya", "pa", "palli", "pan", "pil", "pilli", "pin", "quetzal", "qui", "taca", "tia", "ticue", "tli", "ton", "tonal", "tzal", "tzi", "tzin", "xahual", "xaual", "xiuitl", "xoch", "xochitl", "yah", "yotl", "zoh"];
	var nm4 = ["Achcauhtli", "Ahuiliztli", "Amoxtli", "AmoxtliAtl", "Atl", "Azcalxochitzin", "Centehua", "Chalchiuhticue", "Chalchiuitl", "Chicahua", "Chicomecoatl", "Chimalma", "Chipahua", "Cihuaton", "Citlali", "Citlalli", "Citlalmina", "Coaxoch", "Coszcatl", "Cozamalotl", "Cualli", "Cuicatl", "Eleuia", "Eloxochitl", "Erendira", "Etalpalli", "Eztli", "Huemac", "Huitzilihuitl", "Huitzilli", "Iccauhtli", "Ichtaca", "Icnoyotl", "Ihuicatl", "Ilhicamina", "Ilhuitl", "Itotia", "Itzel", "Itztli", "Iuitl", "Ixcatzin", "Ixchel", "Ixtli", "Izel", "Mahuizoh", "Malinalxochitl", "Manauia", "Mazatl", "Mecatl", "Meztli", "Miahuaxiuitl", "Miyaoaxochitl", "Mizquixahual", "Mizquixaual", "Momoztli", "Moyolehuani", "Nahuatl", "Necahual", "Nelli", "Nenetl", "Nochtli", "Noxochicoztli", "Ohtli", "Papa", "Papan", "Patli", "Quetzal", "Quetzalxochitl", "Quiauhxochitl", "Sacnite", "Teicuih", "Teiuc", "Tenoch", "Teoxihuitl", "Tepin", "Teuicui", "Teyacapan", "Tlachinolli", "Tlaco", "Tlacoehua", "Tlacotl", "Tlahco", "Tlahcoehua", "Tlalli", "Tlanextli", "Tlazohtzin", "Tlexictli", "Tochtli", "Toltecatl", "Tonalnan", "Xihuitl", "Xilonen", "Xiloxoch", "Xiomara", "Xipil", "Xitlalli", "Xiuhcoatl", "Xiuhtonal", "Xochicotzin", "Xochipilli", "Xochiquetzal", "Xochitl", "Xochiyotl", "Xoco", "Xocoh", "Xocoyotl", "Yaotl", "Yaretzi", "Yayauhqui", "Yolihuani", "Yolotli", "Yoloxochitl", "Yoltzin", "Yolyamanitzin", "Zaniyah", "Zeltzin", "Zuma", "Zyanya"];
	var nm5 = ["Aca", "Ach", "Acol", "Ahui", "Amox", "Axa", "Camax", "Chica", "Chimal", "Chipa", "Cipac", "Citla", "Citlal", "Coa", "Coyo", "Cozah", "Cual", "Cuauh", "Cuetlach", "Cuetzpal", "Cuix", "Ehe", "Eloxo", "Etal", "Ez", "Hue", "Huitz", "Huitzi", "Huitzil", "Iccauh", "Ich", "Icno", "Ihui", "Ilhi", "Ilhui", "Ito", "Itz", "Iui", "Ix", "Ixtli", "Mahui", "Mat", "Matlali", "Max", "Maza", "Meca", "Mez", "Mictlan", "Milin", "Miz", "Momoz", "Monte", "Moqui", "Moyole", "Nahua", "Nama", "Natlali", "Neca", "Necal", "Necua", "Nel", "Nezahual", "Noch", "Noche", "Nopal", "Ocelo", "Oh", "Ol", "Ozoma", "Pa", "Quauh", "Quetzal", "Tapa", "Te", "Tecolo", "Teoxi", "Tepil", "Tezca", "Tezo", "Ti", "Tla", "Tlacae", "Tlace", "Tlachi", "Tlal", "Tlanex", "Tlazo", "Tlazoht", "Tlexic", "Tlilpo", "Toch", "Tolteca", "Topil", "Toto", "Uetz", "Xicoh", "Xihui", "Xipil", "Xiuh", "Xochi", "Yao", "Yayauh", "Yolo", "Yolyamani", "Zipac", "Zo", "Zu"];
	var nm6 = ["cali", "camina", "catl", "cauhtli", "cayotl", "chitl", "coatl", "coyotl", "cuintli", "cuix", "hua", "hual", "huani", "huatl", "huitl", "huix", "lal", "laloni", "lan", "lel", "li", "lihuitl", "lin", "liztli", "loc", "lxochitl", "mac", "mapichtli", "metl", "mixtli", "nolli", "palli", "pepe", "pilli", "pin", "popoca", "qui", "taca", "tecol", "tecuhtli", "temoc", "tencatl", "tia", "tic", "tica", "tla", "tli", "tonal", "tonqui", "tzin", "tzotl", "yacatl", "yaxi", "yotli", "zoc", "zoh", "zomoc", "zuma"];


	i = Math.floor(Math.random() * 10); {
		if (type === 1) {
			if (i < 5) {
				rnd = Math.floor(Math.random() * nm4.length);
				names = nm4[rnd];
			} else {
				rnd = Math.floor(Math.random() * nm5.length);
				rnd2 = Math.floor(Math.random() * nm6.length);
				names = nm5[rnd] + nm6[rnd2];
			}
		} else {
			if (i < 5) {
				rnd = Math.floor(Math.random() * nm1.length);
				names = nm1[rnd];
			} else {
				rnd = Math.floor(Math.random() * nm2.length);
				rnd2 = Math.floor(Math.random() * nm3.length);
				names = nm2[rnd] + nm3[rnd2];
			}
		}
		return names;
	}

}