function generator$miscellaneous$book_titles() {
	var choice = $("#radioChoice input[type='radio']:checked").val();
	var names1 = ["agent", "angel", "army", "assassin", "baker", "bandit", "blacksmith", "boy", "butcher", "butterfly", "cat", "changeling", "companion", "criminal", "cyborg", "defender", "doctor", "dog", "duchess", "duke", "emperor", "enemy", "fish", "foe", "foreigner", "friend", "gangster", "giant", "vulture", "descendant", "heir", "child", "creator", "girl", "god", "goddess", "guardian", "hawk", "hero", "horse", "human", "invader", "king", "knight", "lion", "lord", "man", "medic", "mouse", "nymph", "officer", "opponent", "owl", "parrot", "phantom", "pilot", "pirate", "priest", "priestess", "queen", "rat", "raven", "hunter", "rebel", "robot", "sage", "savior", "serpent", "slave", "snake", "soldier", "spider", "spy", "stranger", "swindler", "thief", "tortoise", "traitor", "tree", "turtle", "warrior", "wife", "witch", "wolf", "woman"];
	var names2 = ["agents", "aliens", "armies", "assassins", "bandits", "blacksmiths", "boys", "butchers", "cats", "companions", "criminals", "vultures", "descendants", "heirs", "children", "creators", "defenders", "doctors", "dogs", "enemies", "fish", "foes", "foreigners", "friends", "gangsters", "giants", "girls", "gods", "guardians", "heroes", "horses", "humans", "invaders", "kings", "knights", "lions", "lords", "men", "mice", "officers", "owls", "phantoms", "pilots", "hunters", "pirates", "priests", "rats", "rebels", "robots", "serpents", "slaves", "snakes", "soldiers", "spiders", "spies", "strangers", "swindlers", "thieves", "traitors", "trees", "turtles", "warriors", "wives", "witches", "wolves", "women"];
	var names3 = ["achievement", "ancestry", "anger", "annihilation", "argument", "ascension", "bane", "beginning", "birth", "body", "border", "bow", "carnage", "castle", "cause", "certainty", "chase", "choice", "climax", "completion", "concept", "confinement", "construction", "country", "creation", "crossbow", "culling", "culmination", "curse", "death", "decay", "defeat", "demise", "design", "destiny", "determination", "dishonor", "disruption", "doom", "edge", "effect", "element", "end", "extinction", "faction", "failure", "faith", "family", "fate", "fortune", "foundation", "fruit", "future", "game", "goal", "harmony", "hatred", "history", "honor", "hope", "inception", "influence", "inspiration", "intention", "limit", "loss", "love", "luck", "means", "misfortune", "moon", "murder", "name", "nation", "obliteration", "origin", "perfection", "planet", "restoration", "result", "revenge", "rise", "root", "ruination", "ruins", "scourge", "shield", "source", "spear", "spire", "staff", "star", "strife", "success", "surprise", "sword", "termination", "throne", "tower", "tree", "union", "unity", "vengeance", "victory", "vision", "wand", "will", "world"];
	var names4 = ["of darkness", "of dawn", "of desire", "of despair", "of destruction", "of dread", "of dreams", "of dusk", "of earth", "of eternity", "of fire", "of fortune", "of freedom", "of glory", "of gold", "of greatness", "of heaven", "of hell", "of history", "of hope", "of insanity", "of joy", "of my imagination", "of next year", "of nightmares", "of perfection", "of power", "of rainbows", "of reality", "of silver", "of sorrow", "of stone", "of the ancestors", "of the ancients", "of the banished", "of the curse", "of the day", "of the east", "of the eclipse", "of the end", "of the eternal", "of the forest", "of the forsaken", "of the frontline", "of the gods", "of the great", "of the land", "of the light", "of the lost ones", "of the mountain", "of the nation", "of the night", "of the north", "of the ocean", "of the plague", "of the prison", "of the river", "of the sea", "of the solstice", "of the south", "of the stars", "of the stockades", "of the void", "of the west", "of the world", "of time", "of tomorrow", "of twilight", "of utopia", "of water", "of wind", "of wood", "of yesterday", "with a goal", "with determination", "with gold", "with honor", "with immortality", "with money", "with pride", "with silver", "with sins", "with strength", "with vigor", "with wings", "without a conscience", "without a goal", "without a home", "without courage", "without desire", "without direction", "without duty", "without faith", "without fear", "without flaws", "without glory", "without hate", "without honor", "without hope", "without shame", "without sin", "without time"];
	var names5 = ["accepting", "admiring", "adopting", "altering", "amusing", "answering", "arriving at", "avoiding", "awakening", "bathing in", "battle", "battle of", "battling at", "battling in", "becoming", "begging in", "belonging to", "bound to", "binding to", "bleeding at", "bleeding in", "blinded by", "blinded in", "blood at", "blood in", "bravery in", "breaking", "breath of", "call to", "calling", "challenge of", "challenging", "changing", "chasing", "choking in", "cleaning up", "clinging to", "commanding", "confessions of", "controlling", "crying in", "dancing in", "dead at", "dead in", "death at", "death in", "death to", "deceiving", "delaying", "destroying", "drinking at", "driving into", "dwelling in", "eating at", "eliminating", "ending", "enhancing", "enter", "escape", "escaping", "fade into", "faith of", "fighting", "flee to", "flying into", "force of", "forsaken by", "forsaking", "going to", "growing in", "guarded by", "guarding", "healing", "helping", "hiding", "hunted by", "hunting", "hurt by", "hurting", "ignoring", "inventing", "invited by", "jumping into", "justice in", "kicking", "laughing at", "leading", "learning from", "life at", "life in", "life beneath", "listening to", "losing", "lurking in", "meeting at", "meeting in", "memory of", "mending", "never trust", "origin of", "painting", "pleasing", "possessed by", "praise", "praised by", "prepare for", "preparing for", "promises of", "punished by", "question", "raised by", "reach of", "rejecting", "remember", "rescue at", "rescue in", "right about", "run for", "running in", "sailing into", "scared at", "scared of", "screams at", "screams in", "searching at", "searching for", "searching in", "separated at", "separated by", "separated in", "shelter at", "shelter in", "signs at", "signs in", "signs of", "smile at", "smiles in", "songs of", "sounds in", "sounds of", "starting", "still breathing in", "symbols in", "symbols of", "taste of", "temptations in", "temptations of", "traces in", "travel to", "trust", "vanish at", "vanish in", "vanishing into", "visiting", "walking", "weep for", "welcome to", "whispers in", "whispers of", "write about", "wrong about"];
	var names6 = ["a storm", "dreams", "eternity", "history", "my destiny", "my dreams", "my end", "my enemies", "my family", "my friends", "my future", "my home", "my husband", "my leader", "my nightmares", "my past", "my school", "my wife", "myself", "nature", "nightmares", "secrets", "technology", "the abyss", "the angels", "the animals", "the apocolypse", "the ashes", "the beginning", "the castle", "the champions", "the city", "the commander", "the country", "the dark", "the darkness", "the demons", "the depths", "the dungeons", "the east", "the elements", "the emperor", "the end", "the fires", "the fog", "the forest", "the future", "the graveyard", "the hunter", "the immortals", "the jungle", "the king", "the leaders", "the light", "the maze", "the mines", "the mist", "the moon", "the mountains", "the nation", "the night", "the north", "the ocean", "the past", "the river", "the sea", "the shadows", "the ships", "the slaves", "the south", "the stars", "the sun", "the swamp", "the titans", "the town", "the universe", "the void", "the west", "the world", "time"];
	var names7 = names4;


	switch (choice) {
		case ("children"):
			names1 = ["baby", "bear", "bird", "boy", "bunny", "cat", "caterpillar", "chicken", "cow", "dino", "dog", "dragon", "duck", "family", "fox", "frog", "ghost", "girl", "goat", "kid", "king", "kitten", "lion", "little bird", "little boy", "little dragon", "little duck", "little girl", "little prince", "little princess", "man", "mouse", "owl", "pig", "prince", "princess", "puppy", "queen", "rabbit", "sheep", "snowman", "tiger", "toad", "wizard", "woman"];
			names2 = ["babies", "bears", "birds", "boys", "bunnies", "cats", "chickens", "cows", "dinos", "dogs", "dragons", "ducks", "foxes", "frogs", "ghosts", "girls", "goats", "kids", "kings", "kittens", "lions", "little birds", "little dragons", "little ducks", "mice", "owls", "pigs", "puppies", "rabbits", "sheep", "tigers", "toads", "wizards"];
			names3 = ["adventure", "airplane", "attic", "basement", "bed", "candle", "car", "chair", "chimney", "city", "closet", "coat", "country", "cup", "curiosity", "day", "door", "field", "flower", "forest", "hat", "home", "house", "lantern", "light", "mirror", "mountain", "pocket", "river", "roof", "sands", "shield", "statue", "stories", "story", "tale", "tales", "town", "train", "tree", "wand", "watch", "water", "week", "window"];
			names4 = ["in my house", "in my school", "in my town", "in space", "in the forest", "in the mountains", "in the river", "of dreams", "of excelsior", "of fantasia", "of fantasy", "of fire", "of gold", "of life", "of magic", "of miracles", "of my country", "of my dreams", "of my house", "of my imagination", "of my land", "of mysteries", "of mystery", "of puzzles", "of rain", "of rainbows", "of riddles", "of secrets", "of silver", "of stone", "of sunshine", "of the moon", "of the stars", "of the sun", "of tomorrow", "of utopia", "of wonder", "of wood", "of yesterday", "on the moon"];
			names5 = ["a day with", "adventure of", "afraid of", "amazing life of", "amazing world of", "back to", "back with", "bewitched by", "boring at", "brave at", "bubble of", "careful with", "caring for", "celebrating with", "cleaning at", "cleaning with", "clumsy at", "colors of", "cooking with", "cool at", "crafting with", "crazy at", "crazy with", "cute with", "drawing with", "enchanted by", "fearless with", "foolish with", "free with", "gift from", "gift of", "giving with", "growing up with", "growing with", "happy with", "helping", "jealous of", "jumping with", "learning with", "living with", "love of", "loved by", "playing with", "present from", "present of", "puzzling with", "reading with"];
			names6 = ["fantasy", "flowers", "leaves", "magic", "my best friend", "my brother", "my cat", "my cousin", "my dad", "my dog", "my family", "my father", "my fish", "my friend", "my home", "my house", "my imagination", "my mom", "my mother", "my neighbor", "my neighbors", "my nephew", "my new cat", "my new clothes", "my new dog", "my new fish", "my new pet", "my niece", "my pet", "my pet dragon", "my school", "my sister", "my town", "my village", "petals", "sticks", "the animals", "the doctor", "the fields", "the forest", "the hospital", "the mountains", "the neighbor", "the neighbors", "the river", "the school", "the town", "water"];
			names7 = names4;
			break;
		case ("drama"):
			names1 = ["accomplice", "agent", "ancestor", "angel", "army", "assassin", "assistant", "baker", "bandit", "bearer", "blacksmith", "boy", "bringer", "builder", "butcher", "cat", "child", "collaborator", "collector", "companion", "courier", "creator", "culler", "defender", "deputy", "descendant", "doctor", "dog", "emissary", "enemy", "farmer", "follower", "foreigner", "founder", "friend", "girl", "guardian", "heir", "horse", "human", "invader", "inventor", "knight", "lord", "man", "medic", "messenger", "officer", "opponent", "patron", "peasant", "peon", "pirate", "planner", "rat", "raven", "rebel", "savior", "scientist", "secretary", "servant", "slave", "soldier", "spy", "stranger", "supporter", "thief", "traitor", "vulture", "warrior", "widow", "wife", "witch", "wolf", "woman"];
			names2 = ["agents", "ancestors", "angels", "armies", "assassins", "assistants", "bakers", "bandits", "bearers", "blacksmiths", "boys", "bringers", "builders", "butchers", "children", "collectors", "companions", "couriers", "creators", "cullers", "defenders", "deputies", "descendants", "doctors", "emissaries", "enemies", "farmers", "followers", "foreigners", "founders", "friends", "girls", "guardians", "heirs", "horses", "people", "invaders", "inventors", "knights", "lords", "men", "medics", "messengers", "officers", "opponents", "patrons", "peasants", "peons", "pirates", "planners", "rats", "rebels", "saviors", "scientists", "secretaries", "servants", "slaves", "soldiers", "spies", "strangers", "supporters", "thieves", "traitors", "vultures", "warriors", "widows", "wives", "witches", "wolves", "women"];
			names3 = ["accidents", "anger", "annihilation", "ascension", "bane", "beginning", "birth", "border", "boundaries", "carnage", "castle", "cause", "certainty", "chase", "confinement", "country", "creation", "cruelty", "culling", "death", "decay", "decisions", "demise", "design", "destruction", "dishonor", "disruption", "edge", "effect", "element", "end", "execution", "failure", "fate", "harvest", "homes", "loss", "love", "nation", "obliteration", "origin", "perfection", "planet", "product", "result", "rise", "root", "ruination", "ruins", "scourge", "source", "undoing", "union", "unity", "vengeance", "violence", "vision"];
			names4 = ["dressed in black", "dressed in white", "of afflication", "of agony", "of anguish", "of bad news", "of breaking hearts", "of crime", "of damnation", "of darkness", "of dawn", "of desire", "of despair", "of destruction", "of doom", "of dread", "of dusk", "of earth", "of eternity", "of evil", "of fire", "of fortune", "of freedom", "of glory", "of gold", "of heaven", "of hell", "of history", "of hope", "of ice", "of insanity", "of last rites", "of limbo", "of misery", "of nightmares", "of pain", "of power", "of reality", "of remorse", "of repentance", "of sorrow", "of stone", "of suffering", "of the battle", "of the blues", "of the curse", "of the east", "of the eclipse", "of the end", "of the forest", "of the forsaken", "of the frontline", "of the gods", "of the lost ones", "of the mountains", "of the nation", "of the nether", "of the night", "of the north", "of the ocean", "of the plague", "of the prison", "of the river", "of the sea", "of the south", "of the stars", "of the stockades", "of the void", "of the west", "of the world", "of time", "of tomorrow", "of twilight", "of war", "with a goal", "with debt", "with gold", "with guns", "with hoods", "with horns", "with money", "with silver hair", "with sins", "with wings", "without a conscience", "without a goal", "without a head", "without a home", "without desire", "without direction", "without duty", "without faith", "without fear", "without honor", "without hope", "without shame", "without sin", "without time"];
			names5 = ["accepting", "admiring", "adopting", "alarming", "altering", "answering to", "arrival of", "avoiding", "aware of", "battle", "battle of", "battling", "battling in", "becoming", "begging", "begging in", "belonging to", "bound to", "binding to", "bleeding at", "bleeding in", "blinded by", "blinded in", "blood at", "blood in", "bravery at", "breaking", "breath of", "call to", "calling", "changing", "chasing", "choking in", "cleaning up", "clinging to", "commanding", "confessions of", "cruelty of", "crying in", "dead at", "dead in", "death at", "death in", "death to", "destroying", "driving into", "eliminating", "ending", "enter", "escape", "escaping", "facing", "fade into", "fighting", "flee to", "flying into", "force of", "forsaken by", "forsaking", "frightened of", "haunting", "hiding", "hunted by", "hunting", "hurt by", "hurting", "infamous among", "jealous of", "kicking", "killing", "laughing at", "learning from", "life at", "life in", "listening to", "loathing", "losing", "lurking in", "meeting at", "meeting in", "memories of", "memory of", "mending", "never trust", "numb to", "pray for", "prepare for", "preparing for", "promises of", "remember", "robbing", "run for", "running into", "scared of", "screams at", "screams in", "searching at", "searching for", "searching in", "separated at", "separated by", "separated in", "sick of", "smiles in", "smiles of", "songs of", "sounds of", "starting", "trust", "weep for", "welcome to", "whispers in", "whispers of", "write about", "wrong about"];
			names6 = ["a storm", "dreams", "history", "my destiny", "my dreams", "my end", "my enemies", "my family", "my friends", "my future", "my home", "my husband", "my leader", "my nightmares", "my past", "my school", "my wife", "nightmares", "secrets", "technology", "the abyss", "the apocolypse", "the bridge", "the castle", "the champions", "the city", "the commander", "the country", "the curse", "the dark", "the darkness", "the demons", "the depths", "the dungeons", "the east", "the elements", "the emperor", "the end", "the fog", "the forest", "the future", "the graveyard", "the guards", "the hunter", "the jungle", "the king", "the light", "the mayor", "the maze", "the mines", "the mist", "the moon", "the mountains", "the nation", "the night", "the north", "the ocean", "the past", "the plague", "the president", "the prison", "the prisoner", "the prisoners", "the river", "the sea", "the shadows", "the ships", "the slaves", "the soldier", "the soldiers", "the south", "the stars", "the sun", "the swamp", "the town", "the traitor", "the traitors", "the void", "the west", "the world", "time"];
			names7 = names4;
			break;
		case ("fantasy"):
			names1 = ["agent", "imp", "alien", "angel", "animal", "army", "assassin", "baker", "bandit", "blacksmith", "boy", "butcher", "butterfly", "cat", "changeling", "child", "companion", "creator", "criminal", "cyborg", "deceiver", "defender", "demon", "descendant", "doctor", "dog", "dragon", "dragonborn", "druid", "duchess", "duke", "dwarf", "elf", "emperor", "enchanter", "enemy", "fairy", "fighter", "fish", "foe", "foreigner", "friend", "gangster", "ghost", "giant", "girl", "gnome", "goblin", "god", "goddess", "guardian", "hawk", "heir", "hero", "hobgoblin", "horse", "human", "hunter", "hydra", "invader", "king", "knight", "lion", "lord", "mage", "man", "medic", "mermaid", "merman", "monk", "mouse", "necromancer", "nymph", "officer", "ogre", "opponent", "orc", "owl", "paladin", "parrot", "persuer", "phantom", "pilot", "pirate", "priest", "priestess", "protector", "queen", "rat", "raven", "rebel", "robot", "rogue", "sage", "savior", "serpent", "shaman", "skeleton", "slave", "snake", "soldier", "spider", "spy", "stranger", "summoner", "swindler", "thief", "tortoise", "traitor", "tree", "troll", "turtle", "vampire", "vulture", "warlock", "warrior", "werewolf", "wife", "witch", "wizard", "wolf", "woman", "zombie"];
			names2 = ["agents", "imps", "aliens", "angels", "animals", "armies", "assassins", "bandits", "blacksmiths", "boys", "butchers", "cats", "children", "companions", "creators", "criminals", "cyborgs", "deceivers", "defenders", "demons", "descendants", "doctors", "dogs", "dragons", "druids", "dwarves", "elves", "enchanters", "enemies", "fairies", "fighters", "fish", "foes", "foreigners", "friends", "gangsters", "ghosts", "giants", "girls", "gnomes", "goblins", "gods", "guardians", "heirs", "heroes", "hobgoblins", "horses", "humans", "hunters", "invaders", "kings", "knights", "lions", "lords", "mages", "men", "mermaids", "mermen", "mice", "monks", "necromancers", "nymphs", "officers", "ogres", "orcs", "owls", "paladins", "persuers", "phantoms", "pilots", "pirates", "priests", "protectors", "rats", "rebels", "robots", "rogues", "sages", "serpents", "shamans", "skeletons", "slaves", "snakes", "soldiers", "spiders", "spies", "strangers", "summoners", "swindlers", "thieves", "traitors", "trees", "trolls", "turtles", "vampires", "vultures", "warlocks", "warriors", "werewolves", "witches", "wives", "wizards", "wolves", "women", "zombies"];
			names3 = ["ancestry", "anger", "annihilation", "ascension", "bane", "beginning", "birth", "body", "border", "bow", "burial", "carnage", "castle", "catacomb", "chamber", "chase", "coffin", "completion", "confinement", "construction", "country", "creation", "crossbow", "crypt", "culling", "culmination", "curse", "death", "decay", "defeat", "demise", "destiny", "dishonor", "disruption", "doom", "edge", "element", "enchantment", "end", "extinction", "faction", "failure", "faith", "family", "fate", "fortune", "fruit", "future", "game", "goal", "grave", "harmony", "hatred", "honor", "hope", "imprisonment", "inception", "influence", "inspiration", "limit", "loss", "love", "luck", "magic", "mausoleum", "means", "misfortune", "monument", "moon", "murder", "name", "nation", "obliteration", "origin", "palace", "perfection", "planet", "rebirth", "reincarnation", "renewal", "restoration", "result", "revenge", "revival", "rise", "root", "ruination", "ruins", "scourge", "shield", "source", "spear", "spells", "spire", "staff", "star", "statue", "strife", "success", "surprise", "sword", "termination", "throne", "tomb", "tower", "tree", "union", "unity", "vengeance", "victory", "vision", "wand", "will", "world"];
			names4 = ["of autumn", "of darkness", "of dawn", "of deception", "of demons", "of desire", "of despair", "of destruction", "of the rose", "of doom", "of dread", "of dreams", "of dusk", "of earth", "of eternity", "of fire", "of fortune", "of freedom", "of glory", "of gold", "of greatness", "of heaven", "of hell", "of history", "of hope", "of ice", "of infinity", "of insanity", "of limbo", "of magic", "of misfortune", "of my dreams", "of my imagination", "of nature", "of nightmares", "of perfection", "of power", "of rainbows", "of secrets", "of shadows", "of silver", "of snow", "of sorrow", "of spring", "of stone", "of summer", "of the ancestors", "of the ancients", "of the banished", "of the banner", "of the bow", "of the broken banner", "of the caves", "of the curse", "of the dagger", "of the dungeons", "of the east", "of the eclipse", "of the end", "of the era", "of the eternal", "of the forest", "of the forsaken", "of the future", "of the gods", "of the immortals", "of the king", "of the land", "of the light", "of the lost ones", "of the mountain", "of the nation", "of the night", "of the north", "of the ocean", "of the past", "of the plague", "of the prison", "of the river", "of the sea", "of the shadows", "of the shield", "of the skull", "of the solstice", "of the south", "of the stars", "of the stockades", "of the sword", "of the titans", "of the undead", "of the void", "of the west", "of the wind", "of the world", "of time", "of tomorrow", "of twilight", "of utopia", "of water", "of whispers", "of wind", "of winter", "of wood", "of yesterday", "with a goal", "with determination", "with gold", "with honor", "with immortality", "with money", "with pride", "with silver", "with sins", "with strength", "with vigor", "without a conscience", "without a goal", "without a home", "without a leader", "without courage", "without desire", "without direction", "without duty", "without faith", "without fear", "without flaws", "without glory", "without hate", "without honor", "without hope", "without shame", "without sin", "without time"];
			names5 = ["accepting", "admiring", "adopting", "altering", "amusing", "answering to", "arriving at", "avoiding", "awakening", "bathing in", "battle", "battle of", "battling at", "battling in", "becoming", "begging in", "belonging to", "bound to", "binding to", "bleeding at", "bleeding in", "blinded by", "blinded in", "blood at", "blood in", "bravery at", "breaking", "breath of", "call to", "calling", "challenge of", "challenging", "changing", "chasing", "choking in", "cleaning up", "clinging to", "commanding", "confessions of", "controlling", "crying in", "dancing in", "dead at", "dead in", "death at", "death in", "death to", "deceiving", "delaying", "destroying", "drinking at", "driving into", "dwelling in", "eating at", "eliminating", "ending", "enhancing", "enter", "escape", "escaping", "fade into", "faith of", "fighting", "flee to", "flying into", "force of", "forsaken by", "forsaking", "going to", "growing in", "guarded by", "guarding", "healing", "helping", "hiding", "hunted by", "hunting", "hurt by", "hurting", "ignoring", "inventing", "invited by", "jumping into", "justice in", "kicking", "laughing at", "leading", "learning from", "life at", "life in", "listening to", "losing", "lurking in", "meeting at", "meeting in", "memory of", "mending", "never trust", "origin of", "painting", "pleasing", "possessed by", "praise", "praised by", "prepare for", "preparing for", "promises of", "punished by", "question", "raised by", "reach of", "rejecting", "remember", "rescue at", "rescue in", "right about", "run for", "running in", "sailing into", "scared at", "scared of", "screams at", "screams in", "searching at", "searching for", "searching in", "separated at", "separated by", "separated in", "shelter at", "shelter in", "signs at", "signs in", "signs of", "smile at", "smiles in", "songs of", "sounds in", "sounds of", "starting", "still breathing in", "symbols in", "symbols of", "taste of", "temptations in", "temptations of", "traces in", "travel to", "trust", "vanish at", "vanish in", "vanishing into", "visiting", "walking", "weep for", "welcome to", "whispers in", "whispers of", "winning", "working", "write about", "wrong about"];
			names6 = ["a storm", "dreams", "eternity", "heaven", "hell", "history", "hope", "magic", "my country", "my destiny", "my dreams", "my end", "my enemies", "my family", "my friends", "my future", "my home", "my leader", "my nightmares", "my past", "nature", "nightmares", "secrets", "shields", "spells", "swords", "the abyss", "the ancestors", "the angels", "the animals", "the apocolypse", "the beginning", "the castle", "the catacombs", "the caves", "the champions", "the chasm", "the city", "the commander", "the country", "the curse", "the dark", "the darkness", "the demons", "the depths", "the dungeons", "the east", "the elements", "the emperor", "the end", "the eternals", "the firelands", "the fog", "the forest", "the future", "the gods", "the graves", "the graveyard", "the guardians", "the heavens", "the hills", "the home of demons", "the hunter", "the immortals", "the invaders", "the jungle", "the king", "the leaders", "the light", "the maze", "the mist", "the moon", "the mountains", "the nation", "the night", "the north", "the ocean", "the past", "the phantoms", "the pits", "the plague", "the river", "the sea", "the shadows", "the ships", "the skies", "the slaves", "the south", "the swamp", "the titans", "the tombs", "the town", "the universe", "the void", "the west", "the world", "time"];
			names7 = names4;
			break;
		case ("horror"):
			names1 = ["agent", "angel", "animal", "creature", "figure", "bat", "beast", "boy", "butcher", "cat", "child", "colleague", "cook", "crow", "demon", "devil", "doctor", "dog", "fiend", "fish", "foreigner", "freak", "friend", "ghost", "girl", "guest", "horror", "horse", "human", "hunter", "imp", "man", "monk", "monster", "mutant", "neighbor", "owl", "phantom", "rat", "raven", "serpent", "shaman", "skeleton", "skinner", "snake", "spider", "stranger", "student", "teacher", "tree", "visitor", "vulture", "wife", "witch", "wolf", "woman", "zombie"];
			names2 = ["agents", "angels", "animals", "creatures", "figures", "bats", "beasts", "boys", "butchers", "cats", "children", "colleagues", "cooks", "crows", "demons", "dogs", "fiends", "fish", "foreigners", "freaks", "friends", "ghosts", "girls", "guests", "horrors", "horses", "humans", "hunters", "imps", "men", "monks", "monsters", "mutants", "neighbors", "owls", "phantoms", "rats", "serpents", "skeletons", "snakes", "spiders", "strangers", "students", "teachers", "trees", "visitors", "vultures", "wives", "witches", "wolves", "women", "zombies"];
			names3 = ["ambushed", "blood", "bodies", "books", "captured", "carvings", "corruption", "temptation", "don't go", "don't look", "drawings", "emblems", "eyes", "fire", "footprints", "footsteps", "giggling", "growls", "grunts", "hands", "hidden", "laughter", "lights", "lost", "movement", "mumbling", "music", "noises", "numbers", "paintings", "rituals", "screams", "secrets", "shadows", "signs", "singing", "songs", "sounds", "symbols", "trapped", "trinkets", "vanished", "voices", "whispers", "working"];
			names4 = ["asking questions", "asks weird questions", "at the catacombs", "at the crypts", "at the graveyard", "at the hospital", "at the lake", "at the museum", "at the convention", "at the river", "at the tombs", "behind me", "behind the counter", "behind the door", "behind you", "blinking twice", "during full moon", "during halloween", "during lunch", "following me", "hiding from me", "in apartment B", "in my closet", "in my dreams", "in my garden", "in my nightmares", "in my school", "in my street", "in the abandoned house", "in the antique shop", "in the attic", "in the basement", "in the cabin", "in the castle", "in the elevator", "in the field", "in the fog", "in the forest", "in the lake", "in the library", "in the mirror", "in the mist", "in the mountain", "in the river", "in the store", "looking at me", "next door", "of detention", "of hell", "of the forest", "of the mountain", "of the night", "of the void", "on my roof", "on the ceiling", "under my bed", "who smiles", "who stare", "with a smile", "with black hair", "with fire", "with rotten skin", "with white hair", "without a mouth", "without a voice", "without eyes", "without teeth"];
			names5 = ["abandoned in", "accepting", "afraid of", "afraid in", "alive in", "anguished by", "aware of", "brave until", "blinded by", "calm until", "careful of", "cautious of", "confused by", "corrupted by", "corrupted in", "crazy in", "defiant until", "defiant in", "brave in", "calm in", "defenseless in", "dead in", "evil in", "frozen in", "frightened in", "foolish in", "forsaken in", "fatal in", "growling in", "humble in", "hurt in", "horrified in", "hollowed by", "hidden in", "hidden by", "helpless in", "haunted in", "haunted by", "knowing", "living in", "surviving", "lonely in", "mad in", "miserable until", "mortified in", "motionless in", "mystery in", "numb in", "oblivious to", "oblivious in", "pain in", "pained by", "rotten in", "ready for", "scared by", "scared in", "somber until", "shaking in", "sweating in", "tempting until", "weeping at", "wicked until", "wretched in"];
			names6 = ["eternity", "hell", "history", "my demise", "my dreams", "my end", "my nightmares", "my past", "nature", "nightmares", "secrets", "the abyss", "the catacombs", "the caves", "the chasm", "the city", "the country", "the crypts", "the dark", "the darkness", "the depths", "the dungeons", "the elements", "the end", "the fog", "the forest", "the graves", "the graveyard", "the hills", "the jungle", "the light", "the maze", "the mist", "the mountains", "the night", "the north", "the ocean", "the pits", "the river", "the sea", "the shadows", "the swamp", "the tombs", "the town", "the void", "time"];
			names7 = ["at the catacombs", "at the convention", "at the crypts", "at the graveyard", "at the hospital", "at the lake", "at the museum", "at the river", "at the tombs", "behind me", "behind the counter", "behind the door", "behind you", "during full moon", "during halloween", "during lunch", "following me", "hiding from me", "in apartment B", "in my closet", "in my dreams", "in my garden", "in my nightmares", "in my school", "in my street", "in the abandoned house", "in the antique shop", "in the attic", "in the basement", "in the cabin", "in the castle", "in the catacombs", "in the convention", "in the crypts", "in the elevator", "in the field", "in the fog", "in the forest", "in the graveyard", "in the hospital", "in the lake", "in the library", "in the mirror", "in the mist", "in the mountain", "in the museum", "in the river", "in the store", "in the tombs", "next door", "on my roof", "on the ceiling", "under my bed"];
			break;
		case ("humor"):
			names1 = ["agent", "angel", "baker", "boy", "buffoon", "butcher", "cat", "chicken", "child", "clown", "comedian", "companion", "criminal", "doctor", "dog", "fish", "foreigner", "friend", "girl", "fool", "harlequin", "horse", "hunter", "jester", "king", "knight", "lord", "man", "mime", "mouse", "officer", "parrot", "pig", "prankster", "queen", "rat", "raven", "rebel", "robot", "serpent", "soldier", "spider", "stranger", "thief", "wife", "woman"];
			names2 = names1;
			names3 = ["antics", "bags", "bliss", "buckets", "crying", "electricity", "farts", "fire", "fools", "gags", "humor", "ignorance", "injury", "jokes", "journeys", "laughing", "laughter", "lyrics", "mirrors", "mischief", "parody", "poems", "poop", "pranks", "secrets", "smoke", "songs", "spoofs", "stunts", "traps", "tricking", "tricks", "trinkets", "trouble", "trust", "whispers"];
			names4 = ["of jokes", "of gags", "of humor", "of laughs", "of parody", "of stunts", "with stunts", "of tomorrow", "of the village", "of the city", "of the country", "from the mountains", "from the river", "from the forests", "without a voice", "with big eyes", "project", "gamble", "program", "job", "design", "deal", "plan", "setup", "affair", "program", "scheme", "strategy", "adventure", "exploit", "secret", "in the window", "in the hallway", "in the museum", "on my journey", "during my travel", "arrangement", "delusion", "wish", "puzzle", "makeover", "during the night", "can sing", "left me", "has been naughty", "has a secret life", "on a day out", "with a hat", "mocks me", "prophecy", "can cook", "can dance", "and my journey", "lives with me", "sleeps in my bed", "abroad", "loves sugar", "kicked me out", "stalks me"];
			names5 = ["accomplishment of", "active in", "adored by", "adventure in", "ambition of", "ambitious in", "amused by", "anger of", "angry with", "blinded by", "bliss of", "brilliance of", "bruises of", "charm of", "climax of", "confused by", "confusion of", "damage of", "damaged by", "delight of", "devoted to", "discretion of", "elegance of", "embarrassed by", "evil of", "excited by", "excitement of", "failing of", "favorite of", "frozen by", "glamour of", "glory of", "greed of", "help of", "helped by", "hidden by", "hunger of", "ignorance of", "impressed by", "intelligence of", "intent of", "jealous of", "love for", "love of", "luxury of", "madness of", "mystery of", "offense of", "pleased by", "power of", "puzzled by", "respect for", "shame of", "simplicity of", "song of", "stupidity of", "suspicious of", "tired of", "trust", "trust in", "victory of", "wealth of", "weight of", "whispers of", "word of"];
			names6 = ["being lonely", "fantasy", "fire", "her laugh", "his laugh", "ice", "lies", "magic", "money", "my actions", "my brother", "my design", "my friend", "my friends", "my idea", "my intentions", "my island", "my journey", "my memories", "my parents", "my plan", "my pranks", "my project", "my sister", "my system", "my teacher", "my town", "my trick", "my village", "nature", "that boy", "that girl", "that idiot", "the boy", "the brothers", "the clown", "the design", "the device", "the fool", "the girl", "the guard", "the idea", "the idiot", "the jester", "the job", "the joke", "the king", "the mayor", "the maze", "the night", "the officer", "the pants", "the plan", "the pranks", "the president", "the project", "the sisters", "the teacher", "the town", "the trick", "the truth", "the universe", "the village", "traditions", "water"];
			names7 = names4;
			break;
		case ("mystery"):
			names1 = ["agent", "angel", "army", "assassin", "baker", "bandit", "blacksmith", "boy", "butcher", "butterfly", "cat", "changeling", "companion", "criminal", "cyborg", "defender", "doctor", "dog", "duchess", "duke", "emperor", "enemy", "figure", "fish", "foe", "foreigner", "friend", "gangster", "giant", "vulture", "descendant", "heir", "child", "creator", "girl", "god", "goddess", "guardian", "hawk", "hero", "horse", "human", "invader", "king", "knight", "lion", "lord", "man", "medic", "mouse", "nymph", "officer", "opponent", "owl", "parrot", "phantom", "pilot", "pirate", "priest", "priestess", "queen", "rat", "raven", "hunter", "rebel", "robot", "sage", "savior", "serpent", "slave", "snake", "soldier", "spider", "spy", "stranger", "swindler", "thief", "tortoise", "traitor", "tree", "turtle", "warrior", "wife", "witch", "wolf", "woman"];
			names2 = ["agents", "aliens", "armies", "assassins", "bandits", "blacksmiths", "boys", "butchers", "cats", "companions", "criminals", "vultures", "descendants", "heirs", "children", "creators", "defenders", "doctors", "dogs", "enemies", "figures", "fish", "foes", "foreigners", "friends", "gangsters", "giants", "girls", "gods", "guardians", "heroes", "horses", "humans", "invaders", "kings", "knights", "lions", "lords", "men", "mice", "officers", "owls", "phantoms", "pilots", "hunters", "pirates", "priests", "rats", "rebels", "robots", "serpents", "slaves", "snakes", "soldiers", "spiders", "spies", "strangers", "swindlers", "thieves", "traitors", "trees", "turtles", "warriors", "wives", "witches", "wolves", "women"];
			names3 = ["achievement", "admiration", "appearance", "birth", "ceremony", "city", "clan", "relics", "clouds", "code", "country", "crash", "creed", "cult", "death", "destruction", "dream", "dreams", "enigma", "explosion", "faith", "fantasy", "fascination", "fog", "help", "illusion", "illusions", "key", "magic", "map", "memories", "mists", "mystery", "nightmare", "nightmares", "oracle", "parable", "paradox", "passage", "password", "picure", "prediction", "predictions", "puzzle", "puzzles", "question", "rain", "rebirth", "restoration", "revival", "riddle", "road", "rune", "runes", "seclusion", "secret", "secrets", "sect", "town", "treasure", "village", "vision", "visions", "worship"];
			names4 = ["from beyond the grave", "in my city", "in my country", "in my garden", "in my house", "in my town", "in my village", "in my yard", "in the city", "in the forest", "in the lake", "in the mountains", "in the river", "of a beast", "of a cat", "of a creature", "of a dog", "of a friend", "of a man", "of a painting", "of a person", "of a shadow", "of a star", "of a stranger", "of a woman", "of an asteroid", "of an insect", "of animals", "of darkness", "of history", "of light", "of nature", "of outer space", "of shadows", "of the caves", "of the chasm", "of the flowers", "of the forest", "of the future", "of the galaxy", "of the lake", "of the moon", "of the mountain", "of the nether", "of the ocean", "of the past", "of the river", "of the sea", "of the stars", "of the sun", "of the swamp", "of the underground", "of the void", "of tomorrow", "of yesterday"];
			names5 = ["abandoned by", "accomplishment of", "aching for", "adventure of", "age in", "age of", "alarmed by", "amazed by", "amused by", "ashamed of", "astonished by", "aware of", "blinded by", "bound to", "bravery for", "broken by", "calmed by", "caring for", "cautious of", "celebrate", "celebrated by", "clueless about", "comforted by", "confronted by", "confused by", "conscious of", "corrupted by", "created by", "crushed by", "curse of", "danger of", "deafened by", "death by", "death of", "depths of", "disguised by", "doubting", "enchanted by", "enchantment of", "enlightened by", "essence of", "evil of", "experiences of", "expert in", "faith of", "flaws of", "forsaken by", "frozen by", "gift of", "growing by", "guilt of", "hated by", "hatred of", "help of", "hidden in", "hunger of", "idle in", "jaded by", "love of", "loved by", "loyal to", "luck of", "moral of", "muted by", "nervous in", "old in", "parallel of", "perfume of", "price of", "prize of", "shrouded by", "young in"];
			names6 = ["a storm", "a tower", "darkness", "dreams", "eternity", "heaven", "hell", "history", "hope", "illusions", "light", "my actions", "my destiny", "my dreams", "my future", "my home", "my house", "my life", "my nightmares", "my past", "my secrets", "my sins", "my town", "my village", "nightmares", "the beginning", "the black smoke", "the caves", "the chasm", "the cliffs", "the dark", "the depths", "the dungeon", "the east", "the elements", "the end", "the fog", "the forest", "the future", "the light", "the maze", "the mines", "the mist", "the moon", "the mountains", "the north", "the past", "the river", "the south", "the stars", "the sun", "the west", "the white smoke", "the world", "time", "visions"];
			names7 = names4;
			break;
		case ("nonfiction"):
			names1 = ["horses", "dogs", "people", "men", "women", "athletes", "children", "animals", "cats", "birds", "trees", "flowers", "insects", "fungi", "grasses", "corals", "fish", "reptiles", "amphibians", "rodents", "vultures", "pests", "predators", "preys", "crustaceans", "creatures", "angels", "devils", "demons", "freaks", "fools", "herbs", "spices", "mice", "rats", "warriors", "ancients", "leaders", "followers", "rulers", "kings", "queens", "emperors", "dinosaurs", "spirits", "friends", "enemies", "sinners", "spiders", "snakes", "flies", "stars", "planets", "moons", "ancestors", "politicians"];
			names2 = names1;
			names3 = ["architecture", "art", "awards", "beaches", "books", "buildings", "candles", "capitals", "cars", "castles", "cities", "clans", "comics", "constellations", "constructions", "cooking", "countries", "crafting", "creations", "crimes", "currencies", "customs", "deception", "disasters", "diseases", "drinks", "dungeons", "education", "elements", "empires", "events", "fantasy", "farming", "farms", "festivals", "fields", "fires", "flags", "food", "furniture", "gems", "gods", "gold", "guardians", "guilds", "harmony", "harvest", "help", "holidays", "hope", "instruments", "iron", "languages", "love", "magic", "medicine", "miracles", "money", "monuments", "music", "nations", "nature", "ores", "paintings", "phones", "photos", "planes", "populations", "prisons", "prophets", "resources", "robots", "schools", "science", "secrets", "shields", "ships", "sights", "signs", "silver", "sins", "societies", "spells", "statues", "swords", "technology", "towns", "traditions", "trains", "travelling", "tv", "vehicles", "volcanos", "wars", "waters", "wealth", "weapons", "weather", "wonders", "working"];
			names4 = ["around the world", "in the wild", "in your garden", "of dreams", "of heaven", "of hell", "of history", "of magic", "of medicine", "of our realm", "of science", "of stone", "of technology", "of the caves", "of the decade", "of the depths", "of the east", "of the fields", "of the forest", "of the future", "of the harvest", "of the hunt", "of the jungle", "of the lakes", "of the mountains", "of the north", "of the oceans", "of the past", "of the planet", "of the revolution", "of the rivers", "of the seas", "of the sky", "of the south", "of the swamp", "of the universe", "of the west", "of the world", "of time", "of tomorrow", "of yesterday", "of your dreams", "per continent", "per country", "per realm", "with skills", "with style", "with tradition", "without borders", "without limits", "without restrictions"];
			names5 = ["academics of", "admiration of", "adoration of", "advancement of", "adventures of", "afraid of", "age of", "alarmed by", "alive in", "amazed by", "amazing", "amused by", "amusing", "ancient", "annual", "antique", "aromas of", "athletics of", "awesome", "basic", "blinded by", "bored by", "bored of", "brave", "brilliant", "broken", "cautious of", "classic", "clever", "colors of", "comfort of", "confusing", "creating", "creative", "dangers of", "demand for", "differences of", "digital", "digitize", "elegance of", "emotions of", "ethics of", "excellence of", "excellent", "expert", "experts of", "fame of", "famous", "fantasy of", "father of", "fears of", "flaws of", "focus on", "fortunes of", "friends of", "glamor of", "grace of", "curse of", "memory of", "dawn of", "greed of", "happy", "harmful", "helpful", "hidden", "honest", "honor of", "honored by", "idolized", "infamous", "innocence of", "intelligence of", "intelligent", "joy of", "known", "lasting", "life with", "limits of", "lost", "love for", "love of", "luck of", "majestic", "misery of", "mother of", "mysterious", "mystery of", "nature of", "nifty", "notable", "odd", "outlandish", "perfume of", "political", "popular", "powerful", "precious", "prestigious", "pure", "rare", "respect", "respect for", "safe", "scared of", "scented", "secret", "strange", "stunning", "temptations of", "tempted by", "the best", "united", "united as", "unusual", "wanted", "welcome to", "wonders of"];
			names6 = ["aliens", "androids", "animals", "art", "babies", "biology", "neverland", "chemistry", "children", "cooking", "drawing", "dreams", "earth", "education", "fantasy", "history", "imagination", "keeping pets", "magic", "maths", "medicine", "men", "my country", "my home", "nature", "new earth", "nightmares", "painting", "people", "pets", "physics", "robots", "science", "space", "technology", "teenagers", "the caves", "the depths", "the forest", "the future", "the galaxy", "the lakes", "the lands", "the mountains", "the oceans", "the past", "the planet", "the rivers", "the seas", "the swamps", "the world", "time", "time travel", "today", "tomorrow", "women", "yesterday", "young adults", "your family", "your garden", "your home"];
			names7 = names4;
			break;
		case ("romance"):
			names1 = ["admirer", "angel", "assistant", "beloved", "boy", "boyfriend", "colleague", "cook", "darling", "dear", "dearest", "duchess", "duke", "fianc�", "flame", "foreigner", "friend", "girl", "girlfriend", "god", "goddess", "guest", "heartthrob", "honey", "husband", "knight", "ladylove", "love", "lovebird", "lover", "maid", "man", "mistress", "neighbor", "nymph", "queen", "roommate", "secret admirer", "servant", "stranger", "suitor", "sweetheart", "sweetie", "truelove", "valentine", "visitor", "wife", "woman"];
			names2 = ["admirers", "angels", "assistants", "beloved", "boys", "boyfriends", "butterflies", "darlings", "dears", "dearests", "foreigners", "friends", "girls", "girlfriends", "gods", "guests", "heartthrobs", "honeys", "husbands", "knights", "ladyloves", "loves", "lovebirds", "lovers", "men", "mistresses", "nymphs", "queens", "roommates", "secret admirers", "strangers", "suitors", "sweethearts", "sweeties", "trueloves", "valentines", "visitors", "wifes", "women", "servants", "neighbors", "colleagues"];
			names3 = ["accident", "beginning", "birth", "body", "chase", "choice", "climax", "completion", "creation", "destiny", "determination", "disruption", "edge", "element", "end", "evening", "fluke", "fortune", "foundation", "fruit", "future", "game", "hug", "inspiration", "kiss", "limit", "loss", "love", "luck", "lust", "memory", "name", "night", "origin", "passion", "perfection", "reality", "restoration", "result", "rise", "romance", "root", "scent", "source", "surprise", "vision", "will", "world"];
			names4 = ["at my school", "at my work", "in my town", "in the forest", "in the mountain", "in the night", "in the river", "of the rose", "of bliss", "of dawn", "of desire", "of devotion", "of eternity", "of fire", "of fond memories", "of fortune", "of freedom", "of heaven", "of hell", "of hope", "of insanity", "of joy", "of love", "of lust", "of my admiration", "of my adoration", "of my childhood", "of my dreams", "of my fascination", "of my imagination", "of my mind", "of paradise", "of passion", "of perfection", "of rainbows", "of reality", "of romance", "of silver", "of the evening", "of the forest", "of the mountains", "of the night", "of the north", "of the ocean", "of the river", "of the sea", "of the solstice", "of the south", "of the stars", "of the west", "of tomorrow", "of yearning", "of yesterday", "with a cheeky smile", "with a crush", "with a hat", "with black hair", "with blond hair", "with blue eyes", "with brown hair", "with curly hair", "with freckles", "with funny socks", "with green eyes", "with hazel eyes", "with red hair", "with white hair", "with wings", "without fear", "without flaws", "without shame", "without time"];
			names5 = ["accepting", "aching for", "admiring", "adored by", "adoring", "altering", "amusing", "answering", "assured by", "attracted to", "avoiding", "awakening in", "bathing in", "becoming", "belonging to", "bound to", "blinded by", "breath of", "calling", "changing", "chasing", "clinging to", "comforted by", "confessions of", "dancing with", "controlling", "cuddling", "dance of", "devoted to", "escaping", "excited by", "exciting", "flustered by", "frozen by", "guarded by", "guarding", "happy for", "helping", "hope for", "hunted by", "hurt by", "intelligent", "kind", "kissing", "learning from", "listening to", "lonely without", "losing", "loved by", "loving", "lucky with", "memory of", "oblivious to", "pleasing", "possessed by", "praise", "praised by", "prepare for", "preparing for", "promises of", "punished by", "rejecting", "remember", "scared of", "searching for", "separated by", "smile at", "songs of", "sounds of", "strange", "symbols of", "talk about", "talk to", "taste of", "temptations of", "travel to", "trust", "visited by", "visiting", "walking", "welcome to", "whispers in", "whispers of", "write about", "wrong about"];
			names6 = ["adoration", "affection", "dreams", "eternity", "friendship", "her", "her friends", "her parents", "him", "his friends", "his parents", "love", "lust", "my admirer", "my boyfriend", "my dreams", "my friend", "my future", "my girl", "my girlfriend", "my guy", "my husband", "my man", "my nightmares", "my past", "my secret admirer", "my sweetheart", "my wife", "myself", "passion", "secrets", "the ", "the husband", "the night", "the river", "the sea", "the shadows", "the stars", "the stranger", "the wife", "time"];
			names7 = ["at my school", "at my work", "in my town", "in the forest", "in the mountain", "in the night", "in the river", "of bliss", "of dawn", "of desire", "of devotion", "of eternity", "of fire", "of fond memories", "of fortune", "of freedom", "of heaven", "of hell", "of hope", "of insanity", "of joy", "of love", "of lust", "of my admiration", "of my adoration", "of my childhood", "of my dreams", "of my fascination", "of my imagination", "of my mind", "of paradise", "of passion", "of perfection", "of rainbows", "of reality", "of romance", "of silver", "of the evening", "of the forest", "of the mountains", "of the night", "of the north", "of the ocean", "of the river", "of the sea", "of the solstice", "of the south", "of the stars", "of the west", "of tomorrow", "of yearning", "of yesterday"];
			break;
		case ("sci-fi"):
			names1 = ["agent", "alien", "android", "angel", "army", "assassin", "beast", "boy", "captain", "child", "clone", "commander", "creator", "creature", "cyborg", "defender", "director", "doctor", "droid", "emperor", "enemy", "figure", "foreigner", "friend", "girl", "guardian", "guest", "hero", "human", "hunter", "intruder", "invader", "leader", "man", "martian", "medic", "mercenary", "officer", "pilot", "rebel", "recruit", "robot", "soldier", "spy", "stranger", "traitor", "veteran", "visitor", "volunteer", "woman"];
			names2 = ["agents", "aliens", "androids", "armies", "assassins", "beasts", "boys", "captains", "children", "clones", "commanders", "creators", "creatures", "cyborgs", "defenders", "directors", "doctors", "droids", "emperors", "enemies", "figures", "foreigners", "friends", "girls", "guardians", "guests", "heroes", "humans", "hunters", "intruders", "invaders", "leaders", "men", "martians", "medics", "mercenaries", "officers", "pilots", "rebels", "recruits", "robots", "soldiers", "spies", "strangers", "traitors", "veterans", "visitors", "volunteers", "women"];
			names3 = ["ambush", "appearance", "ascension", "battle", "beginning", "betrayal", "birth", "border", "carnage", "carvings", "chase", "confinement", "construction", "corruption", "creation", "culling", "death", "deception", "defeat", "demise", "destiny", "destruction", "disruption", "doom", "edge", "element", "end", "monument", "monuments", "statue", "statues", "exploration", "extermination", "extinction", "fate", "future", "hatred", "honor", "hope", "inception", "influence", "inspiration", "loss", "love", "monument", "moon", "murder", "nation", "obliteration", "origin", "planet", "rebirth", "reincarnation", "restoration", "result", "revenge", "revival", "rise", "root", "ruins", "scourge", "signs", "source", "star", "statue", "symbols", "throne", "victory", "world"];
			names4 = ["of the sun", "of the moon", "of outer space", "on my ship", "of the galaxy", "of eternity", "from outer space", "of war", "of aliens", "of life", "of death", "of time", "of the dead", "of darkness", "of the void", "of the vacuum", "of the new world", "of earth", "of new earth", "of the sands", "of the ocean", "of the crash", "of the flight", "of the orbit", "of space", "of the worlds", "of the universe", "of the future", "of the past", "of everywhere", "of nowhere", "of the stars", "of stardust", "of moondust", "with tentacles", "with four eyes", "with spaceships", "with a spaceship", "with a UFO", "from the UFO", "in the news", "from the portal", "in the portal", "in the past", "in the future", "in the center of the earth", "in the beginning of time", "of new worlds", "of our legacy", "of men's legacy", "of earth's legacy", "of the fallen", "of our culture", "of honor", "of exploration", "of our ship", "of our destiny", "of our future", "of the outlands", "of sunshine", "of mars", "on mars"];
			names5 = ["abandoned by", "abandoned in", "abandoned on", "admiration for", "afraid of", "alerted by", "alive in", "alive on", "anxious for", "basic", "better", "blindd by", "bored by", "broken", "caution of", "cautious of", "celebrating", "changed by", "closed for", "colors of", "complexity of", "confused by", "courage for", "crazy of", "created by", "cultured by", "darkness of", "defenseless against", "demand for", "dependent on", "devoted to", "disguised by", "disguised in", "elegance of", "equality in", "equality of", "experience in", "experience of", "failing of", "failure of", "father of", "favor of", "fixed in", "fortune of", "frightened of", "frozen by", "gift of", "glory of", "greed of", "haunted by", "hidden by", "hidden in", "inspired by", "intelligence in", "joy of", "life after", "life in", "life with", "light of", "limits of", "lonely in", "longing for", "lost in", "married to", "mother of", "mystery of", "open to", "origin of", "perfection of", "puzzle of", "right for", "secrets of", "security of", "serenity of", "sins of", "stranger to", "understanding"];
			names6 = ["a new war", "a nuclear war", "a nuclear winter", "a rise of machines", "a robot takeover", "aliens", "androids", "droids", "electricity", "eternity", "first contact", "moon rocks", "moondust", "my android servant", "my journey", "my planet", "my space journey", "new earth", "new technology", "orbit", "orbital flight", "outer space", "robotic control", "robots", "solar flares", "space flight", "stardust", "technolic advancements", "technology", "the aliens", "the armies", "the depths", "the end", "the end of earth", "the end of the sun", "the eyes", "the fog", "the galaxy", "the guests", "the immortals", "the intruders", "the legends", "the machines", "the mists", "the moon", "the new age", "the new gods", "the new planet", "the new world", "the ocean", "the portal", "the revolution", "the robotic police", "the secrets", "the secrets of the ocean", "the stars", "the sun", "the titans", "the troopers", "the truth", "the vacuum", "the void", "the void of space", "time travel", "time travellers"];
			names7 = ["from outer space", "of alien life", "of aliens", "of darkness", "of death", "of earth", "of earth's legacy", "of eternity", "of everywhere", "of exploration", "of honor", "of life", "of mars", "of men's legacy", "of moondust", "of new earth", "of new life", "of new worlds", "of nowhere", "of our culture", "of our destiny", "of our future", "of our legacy", "of our ship", "of outer space", "of robots", "of society", "of space", "of stardust", "of sunshine", "of the aliens", "of the androids", "of the crash", "of the dead", "of the droids", "of the faceless ones", "of the fallen", "of the flight", "of the future", "of the galaxy", "of the intruders", "of the invaders", "of the moon", "of the new order", "of the new world", "of the ocean", "of the orbit", "of the outlands", "of the past", "of the planet", "of the sands", "of the stars", "of the sun", "of the universe", "of the vacuum", "of the void", "of the worlds", "of time", "of war", "on mars", "on my ship"];
			break;
	}


	i = Math.floor(Math.random() * 10); {
		if (i < 2) {
			rnd = Math.floor(Math.random() * names1.length);
			rnd2 = Math.floor(Math.random() * names4.length);
			names = names1[rnd] + " " + names4[rnd2];
		} else if (i < 4) {
			rnd = Math.floor(Math.random() * names2.length);
			rnd2 = Math.floor(Math.random() * names4.length);
			names = names2[rnd] + " " + names4[rnd2];
		} else if (i < 6) {
			rnd = Math.floor(Math.random() * names2.length);
			rnd2 = Math.floor(Math.random() * names2.length);
			names = names2[rnd] + " and " + names2[rnd2];
		} else if (i < 8) {
			rnd = Math.floor(Math.random() * names3.length);
			rnd2 = Math.floor(Math.random() * names7.length);
			names = names3[rnd] + " " + names7[rnd2];
		} else {
			rnd = Math.floor(Math.random() * names5.length);
			rnd2 = Math.floor(Math.random() * names6.length);
			names = names5[rnd] + " " + names6[rnd2];
		}
		return names;
	}

}