function generator$miscellaneous$game_soundtracks() {
	var names1 = ["Alien", "Ambient", "Angry", "Animal", "Animalistic", "Autumn", "Background", "Battle", "Beastly", "Bird", "Blessed", "Bone", "Boney", "Boulder", "Bronze", "Burning", "Calm", "Canyon", "Castle", "Cave", "Cavern", "Chaos", "Chaotic", "Christmas", "City", "Corrupt", "Corrupted", "Crystal", "Cursed", "Dark", "Desert", "Diamond", "Distant", "Divine", "Dragon", "Dream", "Dreamy", "Dwarven", "Dwarvish", "Eastern", "Elder", "Electric", "Elven", "Elvish", "Enchanted", "Enemy", "Evening", "Evil", "Fairy", "Family", "Fantasy", "Final", "Fire", "Foreign", "Forest", "Frozen", "Garden", "Ghost", "Giant", "Glacial", "Gnomish", "Goblin", "Golden", "Graveyard", "Heaven", "Heavy", "Hell", "Hope", "Island", "Jungle", "Knight", "Lakeside", "Light", "Lighthouse", "Lonely", "Lonesome", "Love", "Lunar", "Mage", "Magical", "Mammoth", "Medieval", "Midnight", "Miracle", "Monkey", "Morning", "Mountain", "Mystery", "Nightmare", "Noble", "Nomadic", "Northern", "Oasis", "Ocean", "Orbital", "Orc", "Orcish", "Oriental", "Party", "Peace", "Peasant", "Phantom", "Poisoned", "Priest", "Rain", "River", "Royal", "Runic", "Sea", "Seasonal", "Shadow", "Silent", "Silver", "Skeletal", "Snow", "Solar", "Soul", "Southern", "Space", "Spirit", "Spring", "Storm", "Stormy", "Strange", "Summer", "Swamp", "Talking", "Temple", "Thieving", "Tiny", "Tower", "Town", "Troll", "Tunnel", "Twilight", "Undead", "Underground", "Underwater", "Unknown", "Village", "Volcanic", "Volcano", "Voodoo", "War", "Warrior", "Water", "Waterfall", "Wedding", "Western", "Wild", "Winter", "Zombie"];
	var names2 = ["Adventure", "Ale", "Arena", "Armies", "Arrival", "Assault", "Attack", "Autumn", "Battle", "Beast", "Bells", "Blood", "Bow", "Breeze", "Brew", "Business", "Camp", "Cellar", "Chamber", "Champion", "Circus", "City", "Code", "Competition", "Conquest", "Contest", "Control", "Courage", "Creation", "Crown", "Crypt", "Dance", "Danger", "Dilemma", "Dream", "Drums", "Dungeon", "Dynasty", "Escape", "Essence", "Factory", "Faith", "Fanfare", "Feeling", "Fever", "Fight", "Folk", "Games", "Gardens", "Home", "Horrors", "Hunter", "Illusion", "Infiltration", "Invader", "Invasion", "Island", "Journey", "Kingdom", "Knight", "Lair", "Lament", "Lands", "Legend", "Legion", "Life", "Logic", "Lord", "Lullaby", "Madness", "March", "Market", "Medley", "Melody", "Menace", "Mind", "Mine", "Mirage", "Mystery", "Night", "Order", "Party", "People", "Peril", "Power", "Prison", "Quest", "Requiem", "Rescue", "Reunion", "Road", "Ruins", "Rumble", "Sage", "Secret", "Shield", "Ship", "Showdown", "Smoke", "Song", "Spell", "Spring", "Story", "Summer", "Surprise", "Sword", "Tale", "Talk", "Theatre", "Theme", "Tomb", "Tournament", "Town", "Trap", "Tribe", "Village", "Vision", "Voyage", "Walk", "War", "Warning", "Way", "Whisper", "Winter", "Wisdom", "Wonder"];
	var names3 = ["Adventure", "Armies", "Arrival", "Assault", "Attack", "Bandit", "Battle", "Bells", "Blight", "Blood", "Bow", "Bravery", "Call", "Champion", "Choice", "City", "Concern", "Conquest", "Contest", "Courage", "Crown", "Curse", "Dance", "Danger", "Death", "Defender", "Dilemma", "Dread", "Dream", "Drums", "Dungeon", "Dynsasty", "Empire", "Enemy", "Escape", "Faith", "Favor", "Fear", "Fight", "Forest", "Friend", "Games", "Gardens", "Grace", "Guardian", "Hero", "Heroism", "History", "Home", "Hope", "Horror", "Invader", "Invasion", "Island", "Journey", "Kingdom", "Lake", "Lands", "Legend", "Legion", "Life", "Lullaby", "Madness", "March", "Market", "Melody", "Memories", "Memory", "Menace", "Miracle", "Mountain", "Mystery", "Night", "Nightmare", "Ocean", "Order", "Power", "Pride", "Protector", "Quest", "Requiem", "Rescue", "Reunion", "River", "Road", "Ruins", "Sea", "Secret", "Secrets", "Ship", "Song", "Souls", "Spirit", "Surprise", "Swamp", "Sword", "Tale", "Talk", "Terror", "Theme", "Tomb", "Town", "Traitor", "Trap", "Valor", "Village", "Vision", "Voyage", "War", "Warning", "Way", "Whisper", "Wisdom", "Wonders"];
	var names4 = ["Alliances", "Ambition", "Autumn", "Battle", "Beasts", "Brutality", "Chaos", "Conflict", "Culture", "Darkness", "Death", "Desire", "Destiny", "Devotion", "Empathy", "Enchantments", "Favor", "Fortune", "Greed", "Harmony", "Hatred", "History", "Hope", "Hostility", "Isolation", "Joy", "Lethargy", "Life", "Light", "Loss", "Love", "Luck", "Malice", "Might", "Misfortune", "Modesty", "Nature", "Passion", "Peace", "Pity", "Pleasure", "Power", "Prejudice", "Prospect", "Respect", "Serenity", "Silence", "Solitude", "Souls", "Spells", "Spring", "Strife", "Summer", "Surrender", "the Aliens", "the Animals", "the Barbaric", "the Birds", "the Champions", "the Corrupt", "the Cruel", "the Cultured", "the Day", "the Depths", "the Dwarves", "the Elves", "the Explorers", "the Flawed", "the Foreigners", "the Forest", "the Free", "the Future", "the Gnomes", "the Goblins", "the Hidden", "the Holy", "the Honest", "the Innocent", "the Just", "the Kind", "the Land", "the Lost", "the Merchants", "the Moon", "the Moral", "the Mountain", "the Night", "the Ocean", "the Orcs", "the Past", "the People", "the Primitive", "the Pure", "the Righteous", "the River", "the Savage", "the Sea", "the Sick", "the Sky", "the Stars", "the Strangers", "the Strong", "the Sun", "the Tainted", "the Tamed", "the Truth", "the Underground", "the Unholy", "the Untamed", "the Void", "the Weak", "the Wild", "the World", "Tomorrow", "Tragedy", "Tranquility", "Vigor", "Violence", "War", "Winter", "Yesterday"];
	var names5 = ["Adventure's", "Alien's", "Ancestor's", "Angel's", "Army's", "Assassin's", "Autumn's", "Bandit's", "Battle's", "Cavalry's", "Champion's", "Chosen's", "Commander's", "Cook's", "Corruption's", "Courage's", "Dark's", "Death's", "Demon's", "Doom's", "Dragon's", "Dream's", "Dwarf's", "Elf's", "Emperor's", "End's", "Evil's", "Expedition's", "Fallen's", "Fanfare's", "Fever's", "Fight's", "Fire's", "Fortune's", "Genie's", "Ghost's", "Giant's", "Guardian's", "Heaven's", "Hell's", "Hero's", "Hope's", "Kid's", "King's", "Knight's", "Legend's", "Life's", "Light's", "Love's", "Market's", "Mentor's", "Merchant's", "Meteor's", "Minister's", "Miracle's", "Monster's", "Moon's", "Mythic's", "Nature's", "Night's", "Nightmare's", "Ogre's", "Orc's", "Parade's", "Party's", "Peace's", "Pirate's", "Player's", "Prince's", "Prophet's", "Queen's", "Rain's", "Ranger's", "Rogue's", "Ruler's", "Savior's", "Shadow's", "Ship's", "Silence's", "Slayer's", "Snow's", "Spirit's", "Spring's", "Stalker's", "Storm's", "Stranger's", "Summer's", "Sun's", "Thunder's", "Traitor's", "Traveller's", "Tribe's", "Twilight's", "Undead's", "Unknown's", "War's", "Water's", "Wind's", "Winter's", "Wizard's"];
	var names6 = ["Adapting", "Advise", "Alive", "Ambition", "Answer", "Answering", "Appearance", "Appearing", "Approach", "Arrival", "Attacking", "Awakening", "Back", "Balance", "Ballad", "Beauty", "Bite", "Bleeding", "Blemish", "Blind", "Bravery", "Brilliance", "Buzy", "Ceremony", "Challenge", "Changing", "Choice", "Coming", "Confused", "Dance", "Dangerous", "Dead", "Delight", "Departure", "Desire", "Destroyed", "Dirty", "Elegance", "Embrace", "Escape", "Excitement", "Exciting", "Exit", "Fighting", "Fire", "Flaws", "Force", "Forsaken", "Fortitude", "Frenzy", "Frozen", "Glowing", "Grandeur", "Greeting", "Guarding", "Harmony", "Haunted", "Horrors", "Humility", "Humor", "Hunted", "Hunting", "Idea", "Injured", "Invited", "Knocking", "Laughing", "Leaving", "Light", "Love", "Majesty", "Mania", "Might", "Nature", "Passion", "Patience", "Persistence", "Pleased", "Present", "Prevented", "Promise", "Protected", "Quest", "Question", "Rejected", "Requiem", "Resistance", "Return", "Returning", "Revived", "Riding", "Ritual", "Secured", "Serenade", "Serenity", "Simplicity", "Sleeping", "Smiling", "Song", "Splendor", "Style", "Submission", "Surprise", "Talking", "Tranquility", "Transforming", "Travelling", "Trouble", "Troubled", "Tumbling", "Upset", "Watching", "Weakness", "Welcome", "Worship", "Yearning"];
	var names7 = ["Abandoned", "Active", "Admired", "Adorable", "Adored", "Aged", "Aggressive", "Amazing", "Amusing", "Ancient", "Angelic", "Angry", "Anguished", "Aromatic", "Awful", "Awkward", "Barren", "Beautiful", "Bewitched", "Bitter", "Bleak", "Bright", "Brilliant", "Broken", "Calm", "Charming", "Clean", "Cloudy", "Colorful", "Colossal", "Corrupted", "Creepy", "Cruel", "Damaged", "Dark", "Dead", "Dense", "Dirty", "Distant", "Dramatic", "Elegant", "Enchanted", "Evil", "Exciting", "False", "Famous", "Fancy", "Faraway", "Favorite", "Fluffy", "Forsaken", "Frigid", "Frozen", "Funny", "Gentle", "Giant", "Glorious", "Gorgeous", "Graceful", "Grand", "Grim", "Harmless", "Haunted", "Heavenly", "Hidden", "Horrible", "Humble", "Hungry", "Idle", "Impossible", "Infernal", "Invisible", "Little", "Living", "Lonely", "Lost", "Lucky", "Majestic", "Minor", "Mysterious", "Obvious", "Ordinary", "Original", "Other", "Perfect", "Popular", "Puny", "Quiet", "Rare", "Royal", "Safe", "Second", "Secret", "Serene", "Silent", "Smooth", "Strange", "Tragic", "Twin", "Ultimate", "Weird", "Wild", "Worthy"];
	var names8 = ["Adventure", "Alien", "Aliens", "Ancestor", "Animal", "Answer", "Autumn", "Ballad", "Beach", "Beast", "Bird", "Camp", "Canyon", "Castle", "Cliff", "Commander", "Community", "Cook", "Dance", "Desert", "Dungeon", "Dwarf", "Dwarves", "Elf", "Elves", "Emperor", "Expedition", "Family", "Farm", "Feeling", "Fields", "Flower", "Forest", "Garden", "Giant", "Goblin", "Goblins", "Hamlet", "Harbor", "House", "Hunt", "Island", "Journey", "Jungle", "Kid", "King", "Lake", "Light", "Lighthouse", "Lullaby", "Maestro", "Maiden", "Man", "Master", "Melody", "Miracle", "Mission", "Mountain", "Ocean", "Orc", "Orcs", "Pastures", "People", "Person", "Planes", "Planet", "Poem", "Prince", "Princess", "Pursuit", "Pygmy", "Pyramid", "Queen", "Quest", "Question", "Reptile", "River", "Road", "School", "Sea", "Secret", "Serpent", "Ship", "Shrine", "Song", "Spider", "Spirit", "Spring", "Spy", "Storm", "Summer", "Swamp", "Tavern", "Temple", "Territory", "Tomb", "Tower", "Town", "Tree", "Tribute", "Tune", "Vault", "Village", "Volcano", "Voyage", "Waterfall", "Whisper", "Winter", "Woman"];


	i = Math.floor(Math.random() * 10); {
		if (i < 3) {
			rnd = Math.floor(Math.random() * names1.length);
			rnd2 = Math.floor(Math.random() * names2.length);
			names = names1[rnd] + " " + names2[rnd2];
		} else if (i < 5) {
			rnd = Math.floor(Math.random() * names3.length);
			rnd2 = Math.floor(Math.random() * names4.length);
			names = names3[rnd] + " of " + names4[rnd2];
		} else if (i < 7) {
			rnd = Math.floor(Math.random() * names5.length);
			rnd2 = Math.floor(Math.random() * names6.length);
			names = names5[rnd] + " " + names6[rnd2];
		} else {
			rnd = Math.floor(Math.random() * names7.length);
			rnd2 = Math.floor(Math.random() * names8.length);
			names = "The " + names7[rnd] + " " + names8[rnd2];
		}
		return names;
	}

}